### ISSUE TITLE
Unable to start Jupyter NB from dockerized JHub

### ISSUE THREAD

**Issue by hans-permana** [jupyterhub/dockerspawner#101]
I am trying to set up a Jupyterhub server based on Jessica Hamrick's blog (https://developer.rackspace.com/blog/deploying-jupyterhub-for-education/) and I have an issue during the spawning of the Jupyter Notebook. 

My set up is very similar to the one described by Jessica: Jupyterhub running inside a Docker container, configured with dockerspawner (at the moment the single user). When successful, it is supposed to spawn a Jupyter NB (also in a Docker container) on the same machine as the JHub container. In addition, I also use the GitHub oauthentication authenticator.

The authentication works fine. Unfortunately when trying to create a NB, I got these errors on my JHub logging:

```
[I 2016-06-10 08:50:01.963 JupyterHub log:100] 302 GET /user/hans-permana (@10.3.14.133) 9.74ms
[I 2016-06-10 08:50:02.004 JupyterHub dockerspawner:400] Found existing container 'jupyter-hans-permana' (id: cf2fb1d)
[I 2016-06-10 08:50:02.004 JupyterHub dockerspawner:405] Starting container 'jupyter-hans-permana' (id: cf2fb1d)
[W 2016-06-10 08:50:12.004 JupyterHub base:327] User hans-permana server is slow to become responsive
[I 2016-06-10 08:50:12.019 JupyterHub log:100] 302 GET /hub/user/hans-permana (hans-permana@10.3.14.133) 10047.97ms
[I 2016-06-10 08:50:12.025 JupyterHub log:100] 302 GET /user/hans-permana (@10.3.14.133) 1.53ms
[I 2016-06-10 08:50:12.046 JupyterHub log:100] 302 GET /hub/user/hans-permana (hans-permana@10.3.14.133) 11.31ms
[I 2016-06-10 08:50:12.052 JupyterHub log:100] 302 GET /user/hans-permana (@10.3.14.133) 1.47ms
[I 2016-06-10 08:50:12.073 JupyterHub log:100] 302 GET /hub/user/hans-permana (hans-permana@10.3.14.133) 13.45ms
[I 2016-06-10 08:50:12.081 JupyterHub log:100] 302 GET /user/hans-permana (@10.3.14.133) 1.90ms
[I 2016-06-10 08:50:12.100 JupyterHub log:100] 302 GET /hub/user/hans-permana (hans-permana@10.3.14.133) 11.70ms
[I 2016-06-10 08:50:12.106 JupyterHub log:100] 302 GET /user/hans-permana (@10.3.14.133) 1.54ms
[I 2016-06-10 08:50:12.126 JupyterHub log:100] 302 GET /hub/user/hans-permana (hans-permana@10.3.14.133) 11.70ms
[I 2016-06-10 08:50:12.132 JupyterHub log:100] 302 GET /user/hans-permana (@10.3.14.133) 1.46ms
[I 2016-06-10 08:50:12.152 JupyterHub log:100] 302 GET /hub/user/hans-permana (hans-permana@10.3.14.133) 12.03ms
[I 2016-06-10 08:50:12.157 JupyterHub log:100] 302 GET /user/hans-permana (@10.3.14.133) 1.44ms
[I 2016-06-10 08:50:12.176 JupyterHub log:100] 302 GET /hub/user/hans-permana (hans-permana@10.3.14.133) 10.72ms
[I 2016-06-10 08:50:12.183 JupyterHub log:100] 302 GET /user/hans-permana (@10.3.14.133) 1.61ms
[I 2016-06-10 08:50:12.202 JupyterHub log:100] 302 GET /hub/user/hans-permana (hans-permana@10.3.14.133) 10.50ms
[I 2016-06-10 08:50:12.207 JupyterHub log:100] 302 GET /user/hans-permana (@10.3.14.133) 1.00ms
[I 2016-06-10 08:50:12.226 JupyterHub log:100] 302 GET /hub/user/hans-permana (hans-permana@10.3.14.133) 10.04ms
[I 2016-06-10 08:50:12.231 JupyterHub log:100] 302 GET /user/hans-permana (@10.3.14.133) 1.00ms
[I 2016-06-10 08:50:12.249 JupyterHub log:100] 302 GET /hub/user/hans-permana (hans-permana@10.3.14.133) 9.98ms
[I 2016-06-10 08:50:12.255 JupyterHub log:100] 302 GET /user/hans-permana (@10.3.14.133) 0.95ms
[W 2016-06-10 08:50:32.306 JupyterHub user:264] hans-permana's server never showed up at http://127.0.0.1:32812/user/hans-permana after 30 seconds. Giving up
[I 2016-06-10 08:50:32.310 JupyterHub dockerspawner:472] Stopping container jupyter-hans-permana (id: cf2fb1d)
[E 2016-06-10 08:50:32.574 JupyterHub gen:871] Exception in Future <tornado.concurrent.Future object at 0x7f838e1dc780> after timeout
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 867, in error_callback
        future.result()
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 280, in spawn
        raise e
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 256, in spawn
        yield self.server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/orm.py", line 108, in wait_up
        yield wait_for_http_server(self.url, timeout=timeout)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/utils.py", line 94, in wait_for_http_server
        **locals()
    TimeoutError: Server at http://127.0.0.1:32812/user/hans-permana didn't respond in 30 seconds
```

The Jupyter NB container was initially running, and then just died. 

Based on reading some other issues, I am guessing that it is something to do with configuring the IP address of the Hub. I have experimented with it, especially with the property `c.JupyterHub.hub_ip` and `c.DockerSpawner.hub_ip_connect`, but so far I have been unsuccessful. 

Could someone shed some light?

**Comment by minrk** [comment]
When putting the Hub and containers both in docker, it seems to be best to use docker overlay networks. This is what we do in [the docker deployment example](https://github.com/jupyterhub/jupyterhub-deploy-docker). The relevant configuration is [here](https://github.com/jupyterhub/jupyterhub-deploy-docker/blob/master/jupyterhub_config.py#L23).

**Comment by hans-permana** [comment]
Thank you @minrk for pointing me to the deployment instruction. After some more struggles along the instructions, I finally got the jupyterhub running.
