### ISSUE TITLE
home creation issue

### ISSUE THREAD

**Issue by ptulpen** [jupyterhub/dockerspawner#110]
Hello, I try to use dockerspawner with the jupyter/systemuser image, but when I start it I get a message like this
```
Creating user my-user (12345)
/opt/conda/lib/python3.5/site-packages/IPython/paths.py:69: UserWarning: IPython parent '/home/my-user' is not a writable location, using a temp directory.
  " using a temp directory.".format(parent))
Traceback (most recent call last):
  File "/usr/local/bin/jupyterhub-singleuser", line 297, in <module>
    main()
  File "/usr/local/bin/jupyterhub-singleuser", line 293, in main
    return SingleUserNotebookApp.launch_instance()
  File "/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 588, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 1017, in initialize
    super(NotebookApp, self).initialize(argv)
  File "<decorator-gen-6>", line 2, in initialize
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py", line 243, in initialize
    self.migrate_config()
  File "/usr/local/bin/jupyterhub-singleuser", line 219, in migrate_config
    super(SingleUserNotebookApp, self).migrate_config()
  File "/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py", line 169, in migrate_config
    migrate()
  File "/opt/conda/lib/python3.5/site-packages/jupyter_core/migrate.py", line 240, in migrate
    ensure_dir_exists(env['jupyter_config'])
  File "/opt/conda/lib/python3.5/site-packages/ipython_genutils/path.py", line 167, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/opt/conda/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/my-user/.jupyter'
```

my effective config looks like this:

```
c.NotebookApp.allow_origin = '*'
c.JupyterHub.proxy_auth_token =  '#CENSORED'
c.JupyterHub.cookie_secret_file = '/etc/jupyterhub/cookie_secret'
import os


c.JupyterHub.confirm_no_ssl = True

from IPython.utils.localinterfaces import public_ips
c.JupyterHub.hub_ip = public_ips()[0]
c.JupyterHub.spawner_class = 'dockerspawner.SystemUserSpawner'
c.DockerSpawner.container_image = 'jupyter/systemuser'
c.DockerSpawner.remove_containers = True
c.JupyterHub.proxy_api_ip = '0.0.0.0'
c.DockerSpawner.container_ip = '0.0.0.0'
c.DockerSpawner.use_internal_ip = False
c.DockerSpawner.remove_containers = True
c.DockerSpawner.hub_ip_connect = c.JupyterHub.hub_ip

```

so did I forget something?

**Comment by willingc** [comment]
This was likely caused by running with insufficient privileges/permissions.

Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:
