### ISSUE TITLE
Jupyterhub doesn't work with one user

### ISSUE THREAD

**Issue by teored90** [jupyterhub/dockerspawner#148]
I installed jupyterhub on a Ubuntu 16.04 machine with pip and set it to run as a service.
I'm using PAM authentication with system users and `LocalProcessSpawner`.

With one user (user2 in the log) I'm able to login and start the local server normally, but with the other user (user1), which is the one which has sudoer rights and, incidentally, has the same name as the machine, I get a 500 error and `Spawner failed to start [status=1]`

Here is the log after enabling the debug flags:

```
[I 2017-03-13 14:06:39.645 JupyterHub app:724] Loading cookie_secret from /etc/jupyterhub/jupyterhub_cookie_secret
[D 2017-03-13 14:06:39.646 JupyterHub app:796] Connecting to db: sqlite:///jupyterhub.sqlite
[W 2017-03-13 14:06:39.687 JupyterHub app:365] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[I 2017-03-13 14:06:39.695 JupyterHub app:892] Not using whitelist. Any authenticated user will be allowed.
[D 2017-03-13 14:06:39.765 JupyterHub app:1085] Loading state for user1 from db
[D 2017-03-13 14:06:39.766 JupyterHub app:1097] user1 not running.
[D 2017-03-13 14:06:39.770 JupyterHub app:1085] Loading state for user2 from db
[D 2017-03-13 14:06:39.770 JupyterHub app:1097] user2 not running.
[D 2017-03-13 14:06:39.771 JupyterHub app:1102] Loaded users: 
       user1 admin
       user2
[I 2017-03-13 14:06:39.779 JupyterHub app:1453] Hub API listening on http://127.0.0.1:8081/hub/
[I 2017-03-13 14:06:39.783 JupyterHub app:1176] Starting proxy @ http://*:8000/
[D 2017-03-13 14:06:39.783 JupyterHub app:1177] Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '8000', '--api-ip', '127.0.0.1', '--api-port', '8001', '--default-target', 'http://127.0.0.1:8081', '--error-target', 'http://127.0.0.1:8081/hub/error', '--ssl-key', '/etc/letsencrypt/live/mydomain.com/privkey.pem', '--ssl-cert', '/etc/letsencrypt/live/mydomain.com/fullchain.pem']
[D 2017-03-13 14:06:39.991 JupyterHub app:1205] Proxy started and appears to be up
[I 2017-03-13 14:06:39.991 JupyterHub app:1485] JupyterHub is now running at http://127.0.0.1:8000/
[I 2017-03-13 14:06:43.793 JupyterHub log:100] 302 GET /hub/ (@::ffff:130.232.141.152) 2.62ms
[I 2017-03-13 14:06:43.876 JupyterHub log:100] 302 GET /login (@::ffff:130.232.141.152) 1.12ms
[I 2017-03-13 14:06:43.985 JupyterHub log:100] 200 GET /hub/login (@::ffff:130.232.141.152) 30.92ms
[I 2017-03-13 14:06:49.014 JupyterHub spawner:783] Spawning jupyterhub-singleuser '--user="user1"' '--cookie-name="jupyter-hub-token-user1"' '--base-url="/user/user1"' '--hub-host=""' '--hub-prefix="/hub/"' '--hub-api-url="http://127.0.0.1:8081/hub/api"' '--ip="127.0.0.1"' --port=40823 --debug
[D 2017-03-13 14:06:49.027 JupyterHub spawner:584] Polling subprocess every 30s
[W 2017-03-13 14:06:59.085 JupyterHub web:1545] 500 POST /hub/login?next= (::ffff:130.232.141.152): Spawner failed to start [status=1]
[D 2017-03-13 14:06:59.088 JupyterHub base:462] No template for 500
[E 2017-03-13 14:06:59.102 JupyterHub log:99] {
      "Host": "mydomain.com:8000",
      "Content-Type": "application/x-www-form-urlencoded",
      "Cookie": "_ga=GA1.3.1117723039.1474967075; _ga=GA1.2.1117723039.1474967075; arielauth=L9kY5QBllspME23qQTYteQNHnI9PYC+k99exthbfPMOrB71JJVy6Wvv7V8P1g0wYCIVuqXerc0rDOSApAg6FAA==; org.cups.sid=f4397e4912fb45bb52b80b03f01dec2d; _ga=GA1.3.1117723039.1474967075; CASTGC=TGT-604323-qekr0rgkVNeTuBeSclICVCrv7TGAxoThHzkvXKHNWDjIoCfBFz-cas-11; _xsrf=2|76f51ab5|24ade1c92574c1d9fdd8ce7a535e2181|1489399015; username-user1-fisica-unimi-it-9999=\"2|1:0|10:1489400687|35:username-user1-fisica-unimi-it-9999|44:NDc2MzhhMmQ0OWEzNGZlZjg1OTFkMzNlZDYxZTA0Nzg=|4e5cdcea785ca3adeee2e25bdbed0b030b95b74d90e7e06857a04895f35c83b9\"",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "X-Forwarded-Port": "8000",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
      "Referer": "https://mydomain.com:8000/hub/login",
      "X-Forwarded-For": "::ffff:130.232.141.152",
      "Content-Length": "32",
      "Accept-Encoding": "gzip, deflate, br",
      "X-Forwarded-Host": "mydomain.com:8000",
      "Connection": "close",
      "Cache-Control": "max-age=0",
      "X-Forwarded-Proto": "https",
      "Origin": "https://mydomain.com:8000",
      "Upgrade-Insecure-Requests": "1",
      "Accept-Language": "it-IT,it;q=0.8,en-US;q=0.6,en;q=0.4"
    }
[E 2017-03-13 14:06:59.106 JupyterHub log:100] 500 POST /hub/login?next= (@::ffff:130.232.141.152) 10238.15ms
```

**Comment by minrk** [comment]
How are you capturing the logs? I would expect some output that I don't see, which suggests that maybe you are not capturing stderr of the process.

It may be a permission issue, where `user2` can run the notebook server but `user1` cannot. What are the permissions on the `jupyterhub-singleuser` executable and its parent directory?

**Comment by minrk** [comment]
You may also need to check the permissions on Python packages in your environment. Packages installed by one user may not be readable by other users.

**Comment by teored90** [comment]
@minrk OK, thanks to your hint I found the problem. Prior to installing `jupyterhub` I had played with `jupyter` and SSL to use the notebook remotely, using `user1`, which is the administrator user.  This resulted in a non-empty `.jupyter` folder in the home directory that is loaded when `jupyterhub` launches the single-user notebook and creates some conflicts with the certificates.

My mistake with the log files was that I enabled the `extra_log_file` option but, as clearly stated in the comment, this doesn't output the single-user server logs.

This is the relevant part of the log:
```
[D 2017-03-13 18:20:41.524 user1 application:577] Loaded config file: /home/user1/.jupyter/jupyter_notebook_config.py
[D 2017-03-13 18:20:41.525 user1 application:555] Looking for jupyter_notebook_config in /home/user1
[W 2017-03-13 18:20:41.528 user1 configurable:168] Config option `open_browser` not recognized by `SingleUserNotebookApp`.  Did you mean `browser`?
Traceback (most recent call last):
  File "/usr/local/bin/jupyterhub-singleuser", line 6, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/jupyterhub/singleuser.py", line 322, in main
    return SingleUserNotebookApp.launch_instance(argv)
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 1142, in initialize
    self.init_webapp()
  File "/usr/local/lib/python3.5/dist-packages/jupyterhub/singleuser.py", line 295, in init_webapp
    super(SingleUserNotebookApp, self).init_webapp()
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 978, in init_webapp
    xheaders=self.trust_xheaders)
  File "/usr/local/lib/python3.5/dist-packages/tornado/util.py", line 278, in __new__
    instance.initialize(*args, **init_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tornado/httpserver.py", line 155, in initialize
    read_chunk_size=chunk_size)
  File "/usr/local/lib/python3.5/dist-packages/tornado/tcpserver.py", line 112, in __init__
    self.ssl_options['certfile'])
ValueError: certfile "/etc/letsencrypt/live/mydomain.com/fullchain.pem" does not exist
```
