### ISSUE TITLE
500 Uncaught exception GET /tree

### ISSUE THREAD

**Issue by chainkite** [jupyterhub/dockerspawner#177]
When I start jupyterhub/singleuser, got 500 Internal Server Error.

No idea how to set `login_url`.
```
Exception: You must define the 'login_url' setting in your application to use @tornado.web.authenticated
```

Full stack:
```
[E 2017-08-09 02:36:00.514 wxk web:1590](B Uncaught exception GET /tree? (172.17.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/tree?', version='HTTP/1.1', remote_ip='172.17.0.1', headers={'Host': 'localhost:8888', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Kitematic/0.12.0 Chrome/45.0.2454.85 Electron/0.35.4 Safari/537.36', 'Accept-Encoding': 'gzip, deflate', 'Accept-Language': 'en-US', 'Cookie': '_xsrf=2|6a99f920|b013913df09aa203fe15a1721f804161|1502245215'})
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1509, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 2886, in wrapper
        url = self.get_login_url()
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1176, in get_login_url
        self.require_setting("login_url", "@tornado.web.authenticated")
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1390, in require_setting
        "application to use %s" % (name, feature))
    Exception: You must define the 'login_url' setting in your application to use @tornado.web.authenticated
```

**Comment by minrk** [comment]
What's the image tag? What's `conda list` in the image?
