### ISSUE TITLE
Forcing a specific Docker API version?

### ISSUE THREAD

**Issue by Spritekin** [jupyterhub/dockerspawner#197]
Hi,
I'm running the DockerSpawner against a Docker Swarm cluster running on Mesos. The setup works nicely and allows me to spawn notebooks and allow the cluster to scale out or in on demand. 
The problem now is that when I click on the "Stop Server" button I get this error:
```
[I 2017-09-20 01:56:05.307 JupyterHub dockerspawner:519] Stopping container jupyter-grodriguez_40cmcrc_2Ecom (id: 9ddea22)
[E 2017-09-20 01:56:05.310 JupyterHub web:1548] Uncaught exception DELETE /hub/api/users/grodriguez%40cmcrc.com/server (::ffff:172.31.64.124)
HTTPServerRequest(protocol='http', host='uptick.cmcrc.com', method='DELETE', uri='/hub/api/users/grodriguez%40cmcrc.com/server', version='HTTP/1.1', remote_ip='::ffff:172.31.64.124', headers={'Content-Type': 'application/json', 'Accept-Encoding': 'gzip, deflate, br', 'X-Forwarded-For': '::ffff:172.31.64.124', 'X-Forwarded-Host': 'uptick.cmcrc.com', 'X-Requested-With': 'XMLHttpRequest', 'Host':
Traceback (most recent call last):
File "/opt/conda/lib/python3.5/site-packages/tornado/web.py", line 1469, in _execute
result = yield result
File "/opt/conda/lib/python3.5/types.py", line 179, in throw
return self.__wrapped.throw(tp, *rest)
File "/opt/conda/lib/python3.5/site-packages/jupyterhub/apihandlers/users.py", line 188, in delete
yield self.stop_single_user(user)
File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 391, in stop_single_user
yield gen.with_timeout(timedelta(seconds=self.slow_stop_timeout), f)
File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 314, in stop
yield self.spawner.stop()
File "/opt/conda/lib/python3.5/site-packages/dockerspawner/dockerspawner.py", line 520, in stop
yield self.docker('stop', self.container_id)
File "/opt/conda/lib/python3.5/concurrent/futures/_base.py", line 398, in result
return self.__get_result()
File "/opt/conda/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
raise self._exception
File "/opt/conda/lib/python3.5/concurrent/futures/thread.py", line 55, in run
result = self.fn(*self.args, **self.kwargs)
File "/opt/conda/lib/python3.5/site-packages/dockerspawner/dockerspawner.py", line 320, in _docker
return m(*args, **kwargs)
File "/opt/conda/lib/python3.5/site-packages/docker/utils/decorators.py", line 21, in wrapped
return f(self, resource_id, *args, **kwargs)
File "/opt/conda/lib/python3.5/site-packages/docker/api/container.py", line 403, in stop
self._raise_for_status(res)
File "/opt/conda/lib/python3.5/site-packages/docker/client.py", line 174, in _raise_for_status
raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("b'{"message":"client is newer than server (client API version: 1.30, server API version: 1.24)"}'")
```

So essentially the client (DockerSpawner) is running an API 1.30 and Swarm is running 1.24 which makes them unable to communicate during the DELETE command only. As I said it spawns notebooks nicely in the cluster.

I tried adding and env var to my jupyterhub:
ENV DOCKER_API_VERSION 1.24

But it didn't work.

So the question, how may I force the plugin to use a specific API?

I'm using JupyterHub 0.7.2 with DockerSpawner 0.7.0.

Thanks!
Guimo

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo.

I believe the docker client auto-negotiates the API version by default now, so this shouldn't be an issue anymore.
