### ISSUE TITLE
404 error with multiple users

### ISSUE THREAD

**Issue by RobinFrcd** [jupyterhub/dockerspawner#201]
Hi,
Thank you for your work !

I'm currently trying to run my jupyterhub with DockerSpawner, with the following setup:

```
from dockerspawner import DockerSpawner
import netifaces
import os

c.JupyterHub.ip = '127.0.0.1'
c.JupyterHub.port = 8000

c.JupyterHub.spawner_class = DockerSpawner
c.DockerSpawner.extra_host_config = { 'network_mode': 'host' }

docker0 = netifaces.ifaddresses('docker0')
docker0_ipv4 = docker0[netifaces.AF_INET][0]
c.JupyterHub.hub_ip = docker0_ipv4['addr']

notebook_dir = os.environ.get('DOCKER_NOTEBOOK_DIR') or '/home/jovyan/work'
c.DockerSpawner.notebook_dir = notebook_dir

c.DockerSpawner.volumes = { 'jupyterhub-user-{username}': notebook_dir }
c.DockerSpawner.extra_create_kwargs.update({ 'volume_driver': 'local' })

c.DockerSpawner.remove_containers = True
c.Spawner.mem_limit = '2G'
```

Everything works as expected when I run only one server. However, when two users (or more) try to log on the hub, they get a 404 error.
Here are the logs:

```
> [I 2017-10-20 12:08:33.511 JupyterHub dockerspawner:452] Container 'jupyter-testuser' is gone
[I 2017-10-20 12:08:33.527 JupyterHub dockerspawner:508] {'image': 'jupyterhub/singleuser:0.8', 'environment': {'JUPYTERHUB_API_TOKEN': 'b29be60b6e6a4ce1a1ddb0e36ef16ade', 'JPY_API_TOKEN': 'b29be60b6e6a4ce1a1ddb0e36ef16ade', 'JUPYTERHUB_CLIENT_ID': 'user-testuser', 'JUPYTERHUB_HOST': '', 'JUPYTERHUB_OAUTH_CALLBACK_URL': '/user/testuser/oauth_callback', 'JUPYTERHUB_USER': 'testuser', 'JUPYTERHUB_API_URL': 'http://172.17.0.1:8081/hub/api', 'JUPYTERHUB_BASE_URL': '/', 'JUPYTERHUB_SERVICE_PREFIX': '/user/testuser/', 'MEM_LIMIT': '2147483648'}, 'volumes': ['/home/jovyan/work'], 'name': 'jupyter-testuser', 'command': ['start-notebook.sh', '--ip="0.0.0.0"', '--port=8888', '--notebook-dir="/home/jovyan/work"'], 'ports': {'8888/tcp': None}}
{'image': 'jupyterhub/singleuser:0.8', 'environment': {'JUPYTERHUB_API_TOKEN': 'b29be60b6e6a4ce1a1ddb0e36ef16ade', 'JPY_API_TOKEN': 'b29be60b6e6a4ce1a1ddb0e36ef16ade', 'JUPYTERHUB_CLIENT_ID': 'user-testuser', 'JUPYTERHUB_HOST': '', 'JUPYTERHUB_OAUTH_CALLBACK_URL': '/user/testuser/oauth_callback', 'JUPYTERHUB_USER': 'testuser', 'JUPYTERHUB_API_URL': 'http://172.17.0.1:8081/hub/api', 'JUPYTERHUB_BASE_URL': '/', 'JUPYTERHUB_SERVICE_PREFIX': '/user/testuser/', 'MEM_LIMIT': '2147483648'}, 'volumes': ['/home/jovyan/work'], 'name': 'jupyter-testuser', 'command': ['start-notebook.sh', '--ip="0.0.0.0"', '--port=8888', '--notebook-dir="/home/jovyan/work"'], 'ports': {'8888/tcp': None}, 'volume_driver': 'local', 'host_config': {'Memory': 2147483648, 'NetworkMode': 'host', 'Binds': ['jupyterhub-user-testuser:/home/jovyan/work:rw'], 'PortBindings': {'8888/tcp': [{'HostIp': '127.0.0.1', 'HostPort': ''}]}, 'Links': []}}
[I 2017-10-20 12:08:33.598 JupyterHub dockerspawner:543] Created container 'jupyter-testuser' (id: 3e19bc4) from image jupyterhub/singleuser:0.8
[I 2017-10-20 12:08:33.598 JupyterHub dockerspawner:560] Starting container 'jupyter-testuser' (id: 3e19bc4)
[I 2017-10-20 12:08:33.820 JupyterHub base:446] User testuser took 0.451 seconds to start
[I 2017-10-20 12:08:33.822 JupyterHub proxy:231] Adding user testuser to proxy /user/testuser/ => http://127.0.0.1:8888
12:08:33.824 - info: [ConfigProxy] Adding route /user/testuser -> http://127.0.0.1:8888
12:08:33.825 - info: [ConfigProxy] 201 POST /api/routes/user/testuser 
[I 2017-10-20 12:08:33.831 JupyterHub log:122] 302 GET /hub/user/testuser/ \u2192 /user/testuser/?redirects=1 (testuser@46.193.244.35) 466.58ms
[W 2017-10-20 12:09:03.780 JupyterHub base:516] User testuser server stopped, with exit code: ExitCode=1, Error='', FinishedAt=2017-10-20T10:08:35.150864332Z
[I 2017-10-20 12:09:03.780 JupyterHub proxy:254] Removing user testuser from proxy (/user/testuser/)
12:09:03.784 - info: [ConfigProxy] Removing route /user/testuser
12:09:03.785 - info: [ConfigProxy] 204 DELETE /api/routes/user/testuser 
[W 2017-10-20 12:09:03.868 JupyterHub base:516] User testuser server stopped, with exit code: ExitCode=1, Error='', FinishedAt=2017-10-20T10:08:35.150864332Z
[I 2017-10-20 12:09:03.868 JupyterHub proxy:254] Removing user testuser from proxy (/user/testuser/)
12:09:03.871 - warn: [ConfigProxy] 404 DELETE /api/routes/user/testuser 
[E 2017-10-20 12:09:03.872 JupyterHub spawner:754] Unhandled error in poll callback for <dockerspawner.dockerspawner.DockerSpawner object at 0x7fcea9d60ef0>
    Traceback (most recent call last):
      File "/sbin/miniconda3/envs/jabba/lib/python3.6/site-packages/jupyterhub/spawner.py", line 752, in poll_and_notify
        yield gen.maybe_future(callback())
      File "/sbin/miniconda3/envs/jabba/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 518, in user_stopped
        yield self.proxy.delete_user(user, server_name)
      File "/sbin/miniconda3/envs/jabba/lib/python3.6/site-packages/jupyterhub/proxy.py", line 255, in delete_user
        yield self.delete_route(routespec)
    tornado.httpclient.HTTPError: HTTP 404: Not Found
```

Moreover,
When I'm logged on the 2nd account, the jupyer logo link redirects to /users/FIRSTUSER/tree, so I get this error:

> 403 : Forbidden
The error was:
user testuser is not allowed.

Any idea ?

thanks

**Comment by kevcampb** [comment]
You may want to try reverting back to an earlier version of jupyterhub. I've discovered this issue with our configuration. Reverting back to jupyterhub==0.7.2 resolved it. Remember you'll need to remove your sqllite db file.

**Comment by kakal** [comment]
Hi, kevcampb

**Comment by kakal** [comment]
Hi, kevcampb
I get the same error when I used the 0.7.2.

**Comment by kakal** [comment]
Hi, kevcampb
I get the same error when I used the 0.7.2.

Error likes below in jupyterhub.log:
Unhandled error in poll callback for 
    Traceback (most recent call last):
      File "lib/python3.6/site-packages/jupyterhub/spawner.py", line 606, in poll_and_notify
        yield gen.maybe_future(callback())
      File "lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 367, in user_stopped
        yield self.proxy.delete_user(user)
      File "lib/python3.6/site-packages/jupyterhub/orm.py", line 210, in delete_user
        client=client,
    tornado.httpclient.HTTPError: HTTP 404: Not Found

in docker, the error message likes below:
ERROR: the notebook server could not be started because no available port could be found.
I used the **c.DockerSpawner.extra_host_config = { 'network_mode': 'host' }**

Any idea?

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo.

I’m especially closing old “how to” or debugging questions to keep the Issues list to bug reports and feature requests. These can be directed to [the Jupyter forum](http://discourse.jupyter.org) if still relevant.
