### ISSUE TITLE
dockerspawner 0.9.1 does not appear to be compatible with docker==3.x

### ISSUE THREAD

**Issue by Wildcarde** [jupyterhub/dockerspawner#221]
The requirements file leaves it up to pip to as to which docker package should be installed, if you issue a `pip install --upgrade` you will get docker 3 as part of that which results in the following:
```
Feb 14 14:11:00 pynote jupyterhub: [E 2018-02-14 14:11:00.622 JupyterHub user:436] Failed to cleanup gmcgrath's server that failed to start
Feb 14 14:11:00 pynote jupyterhub:     Traceback (most recent call last):
Feb 14 14:11:00 pynote jupyterhub:       File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/jupyterhub/user.py", line 432, in spawn
Feb 14 14:11:00 pynote jupyterhub:         yield self.stop()
Feb 14 14:11:00 pynote jupyterhub:       File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/jupyterhub/user.py", line 501, in stop
Feb 14 14:11:00 pynote jupyterhub:         status = yield spawner.poll()
Feb 14 14:11:00 pynote jupyterhub:       File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/dockerspawner/dockerspawner.py", line 421, in poll
Feb 14 14:11:00 pynote jupyterhub:         container = yield self.get_container()
Feb 14 14:11:00 pynote jupyterhub:       File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/dockerspawner/dockerspawner.py", line 447, in get_container
Feb 14 14:11:00 pynote jupyterhub:         'inspect_container', self.container_name
Feb 14 14:11:00 pynote jupyterhub:       File "/opt/rh/rh-python35/root/usr/lib64/python3.5/concurrent/futures/_base.py", line 398, in result
Feb 14 14:11:00 pynote jupyterhub:         return self.__get_result()
Feb 14 14:11:00 pynote jupyterhub:       File "/opt/rh/rh-python35/root/usr/lib64/python3.5/concurrent/futures/_base.py", line 357, in __get_result
Feb 14 14:11:00 pynote jupyterhub:         raise self._exception
Feb 14 14:11:00 pynote jupyterhub:       File "/opt/rh/rh-python35/root/usr/lib64/python3.5/concurrent/futures/thread.py", line 55, in run
Feb 14 14:11:00 pynote jupyterhub:         result = self.fn(*self.args, **self.kwargs)
Feb 14 14:11:00 pynote jupyterhub:       File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/dockerspawner/dockerspawner.py", line 408, in _docker
Feb 14 14:11:00 pynote jupyterhub:         m = getattr(self.client, method)
Feb 14 14:11:00 pynote jupyterhub:       File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/dockerspawner/dockerspawner.py", line 62, in client
Feb 14 14:11:00 pynote jupyterhub:         client = docker.APIClient(**kwargs)
Feb 14 14:11:00 pynote jupyterhub:       File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/docker/api/client.py", line 110, in __init__
Feb 14 14:11:00 pynote jupyterhub:         config_dict=self._general_configs
Feb 14 14:11:00 pynote jupyterhub:     TypeError: load_config() got an unexpected keyword argument 'config_dict'
```

Rolling docker back to 2.7.0 resolved the issue, I have not tested 3.x with dockerspawner 0.8.1 but 2.7 works well with that as well.

**Comment by sangramga** [comment]
@minrk @willingc Please take a look at this. Really major issue. Thanks in advance!!

**Comment by sangramga** [comment]
@Wildcarde Probably found a fix. Although not tested. Seems to be an issue with docker-py API. 
Refer to [https://github.com/docker/docker-py/issues/1968](https://github.com/docker/docker-py/issues/1968)

**Comment by minrk** [comment]
I just tested DockerSpawner with docker-py 3.2.1 and it worked without issue. Maybe there's no issue here?

**Comment by dhirschfeld** [comment]
I'm running DockerSpawner master with docker-py 3.2.1 and am not seeing this problem.

The error is unusual since the `load_config` function does have a `config_dict` kwarg:

[`docker/api/client.py#L109-L111`](https://github.com/docker/docker-py/blob/master/docker/api/client.py#L109-L111)
```python
        self._auth_configs = auth.load_config(
            config_dict=self._general_configs
        )
```
[`docker/auth.py#L227-L238`](https://github.com/docker/docker-py/blob/16751ac509b4bbe75293847fe87099ff51a74013/docker/auth.py#L227-L238)
```python
def load_config(config_path=None, config_dict=None):
    """
    Loads authentication data from a Docker configuration file in the given
    root directory or if config_path is passed use given path.
    Lookup priority:
        explicit config_path parameter > DOCKER_CONFIG environment variable >
        ~/.docker/config.json > ~/.dockercfg
    """

    if not config_dict:
        config_file = config.find_config_file(config_path)
```

**Comment by willingc** [comment]
It looks as if this was due to an upstream docker issue that has been resolved. You may need to uninstall and reinstall docker as mentioned in this issue https://github.com/docker/docker-py/issues/1968#issuecomment-376339745

**Comment by minrk** [comment]
Thanks, @willingc!
