### ISSUE TITLE
SystemUserSpawner can't spawn Docker Container

### ISSUE THREAD

**Issue by Energy23** [jupyterhub/dockerspawner#238]
Hello community,
I have a problem with using Systemuserspawner,
I already ran a local VM with same configuration, but now with a fresh install the SystemUserSpawner can't run a Docker Container, I've tried several Docker Images

Config is
Debian Strech
JupyterHub 0.9
Dockerspawner 0.10
with config.py

```
import os
c.JupyterHub.hub_ip = '0.0.0.0'

c.JupyterHub.spawner_class = 'dockerspawner.SystemUserSpawner'
c.SystemUserSpawner.host_homedir_format_string = '/home/{username}'
c.DockerSpawner.image = 'jupyter/base-notebook:latest'

c.Authenticator.admin_users = set({'andyg'})

c.LocalAuthenticator.create_system_users = True

c.JupyterHub.hub_ip = public_ips()[0]

```

This is the log of the Docker container:

```
docker logs 9f23364de255
/usr/local/bin/start-singleuser.sh: ignoring /usr/local/bin/start-notebook.d/*

Set username to: andyg
Set andyg UID to: 46971
Executing the command: jupyterhub-singleuser --ip="0.0.0.0" --port=8888
[W 2018-06-22 11:10:28.946 SingleUserNotebookApp configurable:168] Config option `open_browser` not recognized by `SingleUserNotebookApp`.  Did you mean `browser`?
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/jupyterhub-singleuser", line 6, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 455, in main
    return SingleUserNotebookApp.launch_instance(argv)
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1535, in initialize
    self.init_configurables()
  File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1233, in init_configurables
    connection_dir=self.runtime_dir,
  File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/opt/conda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/conda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/conda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/conda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/andyg/.local'
```

So I know what the Problem is. There is no write permission in the /home/{username} folder, but how do I resolve this issue?

Thanks in advance, great community here!

**Comment by SolarisYan** [comment]
ls  -ld /home/andyg
you will see it's own is root:root
You can chown andyg:andyg /home/andyg -R to solve it. 
But i don't know why and on centos it's ok.
Maybe it's a bug on Debian

**Comment by Energy23** [comment]
I solved the Problem with a short Python Script in jupyterhub_config.py

```
from pwd import getpwnam
def fix_dir_hook(spawner):
    username = spawner.user.name # get the username
    home_path = os.path.join('/home', username)
    if not os.path.exists(home_path):
        os.chdir('/home')
        os.mkdir(username)
    uid = getpwnam(username).pw_uid
    os.chown(home_path, uid, 100)
    pass
```
