### ISSUE TITLE
When configuring Jupyterhub to use dockerspawner class SwarmSpawner fails to import EndpointSpec

### ISSUE THREAD

**Issue by blokjonathan** [jupyterhub/dockerspawner#294]
**Describe the bug**
After configuring Jupyterhub to use dockerspawner the library 'docker' is used. This library is imported using pip. The latest version of this library (version==3.7.0) no longer includes the class EndpointSpec. I was able to fix this by stepping the version for docker down to 3.6.0.

**To Reproduce**
1. Install Jupyterhub and required packages
2. Configure Jupyterhub to use dockerspawner and install required packages
3. Make sure the version of 'docker' installed by pip is 3.7.0
4. Try to start Jupyterhub

**Expected behavior**
Jupyterhub should not rely on deprecated classes.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Redhat

**Additional context**
import dockerspawner
Traceback (most recent call last):
File "", line 1, in 
File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/dockerspawner/init.py", line 3, in 
from .swarmspawner import SwarmSpawner
File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/dockerspawner/swarmspawner.py", line 8, in 
from docker.types import (
ImportError: cannot import name 'EndpointSpec'

**Comment by minrk** [comment]
I think perhaps there is a corrupted installation of the docker package. `docker.types.EndpointSpec` [is present in docker-py 3.7](https://github.com/docker/docker-py/blob/3.7.0/docker/types/__init__.py#L7), and is not deprecated. You might try removing and reinstalling `docker`.

The given reproduction steps result in a working jupyterhub with swarmspawner for me:

<details>

```
$ pip list
Package           Version
----------------- --------
alembic           1.0.8
async-generator   1.10
certifi           2019.3.9
chardet           3.0.4
decorator         4.4.0
docker            3.7.0
docker-pycreds    0.4.0
dockerspawner     0.11.0
escapism          1.0.0
idna              2.8
ipython-genutils  0.2.0
Jinja2            2.10
jupyterhub        0.9.4
Mako              1.0.8
MarkupSafe        1.1.1
pamela            1.0.0
pip               18.1
prometheus-client 0.6.0
python-dateutil   2.8.0
python-editor     1.0.4
python-oauth2     1.1.0
requests          2.21.0
setuptools        40.6.2
six               1.12.0
SQLAlchemy        1.3.1
tornado           6.0.2
traitlets         4.3.2
urllib3           1.24.1
websocket-client  0.56.0
```

</details>
