### ISSUE TITLE
404 : Not Found Error when Spawning User Container

### ISSUE THREAD

**Issue by playermanny2** [jupyterhub/dockerspawner#295]
Hi,

I have a couple containers(jupyterhub and jupyter single user notebook) based off the https://github.com/jupyterhub/jupyterhub-deploy-docker -- some slight modifications were made to remove oauthauthentication and postgresdb

The jupyterhub container is able to run fine, as the log-in page is accessible as expected. The problem comes when logging in as a user, the container seems to spin up, but not be accessible as a 404 error occurs after a successful login

I am using https://github.com/jupyterhub/jupyterhub-deploy-docker/tree/master/examples/custom-notebook-server as the custom notebook image that is spawned for by dockerspawner.

So far I've already tried some fixes as directed by previous post issues, to no avail:
1. Install jupyterhub inside notebook image ( this removed the 404 error, but caused 500 errors. the container appeared to never spin up
2. Modifying spawn cmd to activate conda environment  

Any help would be appreciated, as I'm kind of stumped on what the issue is!

Container Logs

```
jupyterhub | [W 2019-04-09 17:20:14.761 JupyterHub app:441] JupyterHub.debug_proxy is deprecated in JupyterHub 0.8, use ConfigurableHTTPProxy.debug
jupyterhub | [I 2019-04-09 17:20:14.761 JupyterHub app:1673] Using Authenticator: jupyterhub.auth.PAMAuthenticator-0.9.4
jupyterhub | [I 2019-04-09 17:20:14.761 JupyterHub app:1673] Using Spawner: dockerspawner.dockerspawner.DockerSpawner-0.10.0
jupyterhub | [I 2019-04-09 17:20:14.765 JupyterHub app:1016] Loading cookie_secret from /data/jupyterhub_cookie_secret
jupyterhub | [I 2019-04-09 17:20:14.783 JupyterHub proxy:431] Generating new CONFIGPROXY_AUTH_TOKEN
jupyterhub | [E 2019-04-09 17:20:14.812 JupyterHub app:1222] Error adding user jovyan already in db
jupyterhub |     Traceback (most recent call last):
jupyterhub |       File "/opt/conda/lib/python3.6/site-packages/jupyterhub/app.py", line 1220, in init_users
jupyterhub |         await maybe_future(self.authenticator.add_user(user))
jupyterhub |       File "/opt/conda/lib/python3.6/site-packages/jupyterhub/auth.py", line 525, in add_user
jupyterhub |         raise KeyError("User %s does not exist." % user.name)
jupyterhub |     KeyError: 'User jovyan does not exist.'
jupyterhub |
jupyterhub | [W 2019-04-09 17:20:14.814 JupyterHub app:1234]
jupyterhub |     You can set
jupyterhub |         c.Authenticator.delete_invalid_users = True
jupyterhub |     to automatically delete users from the Hub database that no longer pass
jupyterhub |     Authenticator validation,
jupyterhub |     such as when user accounts are deleted from the external system
jupyterhub |     without notifying JupyterHub.
jupyterhub |
jupyterhub | [I 2019-04-09 17:20:14.829 JupyterHub app:1855] Hub API listening on http://jupyterhub:8080/hub/
jupyterhub | [I 2019-04-09 17:20:14.830 JupyterHub proxy:567] Starting proxy @ http://:8443/
jupyterhub | 17:20:15.241 - info: [ConfigProxy] Proxying https://*:8443 to (no default)
jupyterhub | 17:20:15.243 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
jupyterhub | 17:20:15.386 - info: [ConfigProxy] 200 GET /api/routes
jupyterhub | [I 2019-04-09 17:20:15.386 JupyterHub proxy:301] Checking routes
jupyterhub | [I 2019-04-09 17:20:15.386 JupyterHub proxy:370] Adding default route for Hub: / => http://jupyterhub:8080
jupyterhub | 17:20:15.388 - info: [ConfigProxy] Adding route / -> http://jupyterhub:8080
jupyterhub | 17:20:15.389 - info: [ConfigProxy] 201 POST /api/routes/
jupyterhub | [I 2019-04-09 17:20:15.389 JupyterHub app:1912] JupyterHub is now running at http://:8443/
jupyterhub | 17:20:16.059 - debug: [ConfigProxy] PROXY WEB / to http://jupyterhub:8080
jupyterhub | [I 2019-04-09 17:20:16.069 JupyterHub log:158] 302 GET / -> /hub (@::ffff:73.70.187.70) 0.99ms
jupyterhub | 17:20:16.100 - debug: [ConfigProxy] PROXY WEB /hub to http://jupyterhub:8080
jupyterhub | [I 2019-04-09 17:20:16.102 JupyterHub log:158] 302 GET /hub -> /hub/ (@::ffff:73.70.187.70) 0.56ms
jupyterhub | 17:20:16.438 - debug: [ConfigProxy] PROXY WEB /hub/ to http://jupyterhub:8080
jupyterhub | [I 2019-04-09 17:20:16.450 JupyterHub log:158] 302 GET /hub/ -> /user/almore.cato/ (almore.cato@::ffff:73.70.187.70) 8.77ms
jupyterhub | 17:20:16.673 - debug: [ConfigProxy] PROXY WEB /user/almore.cato/ to http://jupyterhub:8080
jupyterhub | 17:20:16.851 - debug: [ConfigProxy] PROXY WEB / to http://jupyterhub:8080
jupyterhub | [I 2019-04-09 17:20:16.853 JupyterHub log:158] 302 GET / -> /hub (@::ffff:73.70.187.70) 0.58ms
jupyterhub | 17:20:16.902 - debug: [ConfigProxy] PROXY WEB /hub to http://jupyterhub:8080
jupyterhub | [I 2019-04-09 17:20:16.904 JupyterHub log:158] 302 GET /hub -> /hub/ (@::ffff:73.70.187.70) 0.51ms
jupyterhub | 17:20:17.106 - debug: [ConfigProxy] PROXY WEB /hub/ to http://jupyterhub:8080
jupyterhub | [I 2019-04-09 17:20:17.114 JupyterHub log:158] 302 GET /hub/ -> /user/almore.cato/ (almore.cato@::ffff:73.70.187.70) 6.65ms
jupyterhub | 17:20:17.305 - debug: [ConfigProxy] PROXY WEB /user/almore.cato/ to http://jupyterhub:8080
jupyterhub | [I 2019-04-09 17:20:17.308 JupyterHub log:158] 302 GET /user/almore.cato/ -> /hub/user/almore.cato/ (@::ffff:73.70.187.70) 0.57ms
jupyterhub | 17:20:17.695 - debug: [ConfigProxy] PROXY WEB /hub/user/almore.cato/ to http://jupyterhub:8080
jupyterhub | [W 2019-04-09 17:20:17.706 JupyterHub dockerspawner:158] DockerSpawner.container_image is deprecated in dockerspawner 0.9.  Use DockerSpawner.image
jupyterhub | [W 2019-04-09 17:20:17.744 JupyterHub dockerspawner:684] Removing container that should have been cleaned up: jupyter-almore_2Ecato (id: 21e4f3a)
jupyterhub | [I 2019-04-09 17:20:17.744 JupyterHub dockerspawner:595] Removing container 21e4f3af686d579fc1d09ca8d7fb9237d591af96a7345be89815b5b96936c46e
jupyterhub | [I 2019-04-09 17:20:17.875 JupyterHub dockerspawner:698] Created container jupyter-almore_2Ecato (id: 706abb5) from image jupyterhub-test
jupyterhub | [I 2019-04-09 17:20:17.875 JupyterHub dockerspawner:721] Starting container jupyter-almore_2Ecato (id: 706abb5)
jupyterhub | [W 2019-04-09 17:20:19.707 JupyterHub _version:30] Single-user server has no version header, which means it is likely < 0.8. Expected 0.9.4
jupyterhub | [I 2019-04-09 17:20:19.707 JupyterHub base:628] User almore.cato took 2.002 seconds to start
jupyterhub | [I 2019-04-09 17:20:19.708 JupyterHub proxy:242] Adding user almore.cato to proxy /user/almore.cato/ => http://172.20.0.3:8888
jupyterhub | 17:20:19.709 - info: [ConfigProxy] Adding route /user/almore.cato -> http://172.20.0.3:8888
jupyterhub | 17:20:19.709 - info: [ConfigProxy] 201 POST /api/routes/user/almore.cato
jupyterhub | [I 2019-04-09 17:20:19.710 JupyterHub log:158] 302 GET /hub/user/almore.cato/ -> /user/almore.cato/?redirects=1 (almore.cato@::ffff:73.70.187.70) 2012.92ms
jupyterhub | 17:20:20.020 - debug: [ConfigProxy] PROXY WEB /user/almore.cato/?redirects=1 to http://172.20.0.3:8888
jupyterhub | 17:20:20.044 - debug: [ConfigProxy] PROXY WEB /user/almore.cato/?redirects=1 to http://172.20.0.3:8888
jupyterhub | 17:20:20.073 - debug: [ConfigProxy] PROXY WEB /user/almore.cato/?redirects=1 to http://172.20.0.3:8888
jupyterhub | 17:20:20.092 - debug: [ConfigProxy] PROXY WEB /user/almore.cato/?redirects=1 to http://172.20.0.3:8888
jupyterhub | 17:20:20.125 - debug: [ConfigProxy] PROXY WEB /user/almore.cato/?redirects=1 to http://172.20.0.3:8888
jupyterhub | 17:20:20.153 - debug: [ConfigProxy] PROXY WEB /user/almore.cato/?redirects=1 to http://172.20.0.3:8888
jupyterhub | 17:20:20.178 - debug: [ConfigProxy] PROXY WEB /user/almore.cato/?redirects=1 to http://172.20.0.3:8888
jupyterhub | 17:20:20.241 - debug: [ConfigProxy] PROXY WEB /user/almore.cato/?redirects=1 to http://172.20.0.3:8888
jupyterhub | 17:20:20.274 - debug: [ConfigProxy] PROXY WEB /user/almore.cato/?redirects=1 to http://172.20.0.3:8888
jupyterhub | 17:20:20.299 - debug: [ConfigProxy] PROXY WEB /user/almore.cato/?redirects=1 to http://172.20.0.3:8888
jupyterhub | 17:20:20.327 - debug: [ConfigProxy] PROXY WEB /user/almore.cato/?redirects=1 to http://172.20.0.3:8888
jupyterhub | 17:20:20.407 - debug: [ConfigProxy] PROXY WEB /user/almore.cato/?redirects=1 to http://172.20.0.3:8888
jupyterhub | 17:20:20.440 - debug: [ConfigProxy] PROXY WEB /user/almore.cato/?redirects=1 to http://172.20.0.3:8888
jupyterhub | 17:20:20.461 - debug: [ConfigProxy] PROXY WEB /user/almore.cato/?redirects=1 to http://172.20.0.3:8888
jupyterhub | 17:20:20.486 - debug: [ConfigProxy] PROXY WEB /user/almore.cato/?redirects=1 to http://172.20.0.3:8888
jupyterhub | 17:20:32.663 - debug: [ConfigProxy] PROXY WEB / to http://jupyterhub:8080
jupyterhub | [I 2019-04-09 17:20:32.666 JupyterHub log:158] 302 GET / -> /hub (@::ffff:73.70.187.70) 0.63ms
jupyterhub | 17:20:32.688 - debug: [ConfigProxy] PROXY WEB /hub to http://jupyterhub:8080
jupyterhub | [I 2019-04-09 17:20:32.689 JupyterHub log:158] 302 GET /hub -> /hub/ (@::ffff:73.70.187.70) 0.51ms
jupyterhub | 17:20:33.104 - debug: [ConfigProxy] PROXY WEB /hub/ to http://jupyterhub:8080
jupyterhub | [I 2019-04-09 17:20:33.112 JupyterHub log:158] 302 GET /hub/ -> /user/almore.cato/ (almore.cato@::ffff:73.70.187.70) 6.57ms
jupyterhub | 17:20:33.437 - debug: [ConfigProxy] PROXY WEB /user/almore.cato/ to http://172.20.0.3:8888
jupyterhub | 17:20:33.502 - debug: [ConfigProxy] PROXY WEB /user/almore.cato to http://172.20.0.3:8888
jupyterhub | 17:20:33.619 - debug: [ConfigProxy] PROXY WEB /static/components/jquery-ui/themes/smoothness/jquery-ui.min.css?v=9b2c8d3489227115310662a343fce11c to http://jupyterhub:8080
jupyterhub | [I 2019-04-09 17:20:33.621 JupyterHub log:158] 302 GET /static/components/jquery-ui/themes/smoothness/jquery-ui.min.css?v=9b2c8d3489227115310662a343fce11c -> /hub/static/components/jquery-ui/themes/smoothness/jquery-ui.min.css?v=9b2c8d3489227115310662a343fce11c (@::ffff:73.70.187.70) 0.66ms
jupyterhub | 17:20:33.858 - debug: [ConfigProxy] PROXY WEB /static/components/jquery-typeahead/dist/jquery.typeahead.min.css?v=7afb461de36accb1aa133a1710f5bc56 to http://jupyterhub:8080
jupyterhub | [I 2019-04-09 17:20:33.860 JupyterHub log:158] 302 GET /static/components/jquery-typeahead/dist/jquery.typeahead.min.css?v=7afb461de36accb1aa133a1710f5bc56 -> /hub/static/components/jquery-typeahead/dist/jquery.typeahead.min.css?v=7afb461de36accb1aa133a1710f5bc56 (@::ffff:73.70.187.70) 0.61ms
jupyterhub | 17:20:33.873 - debug: [ConfigProxy] PROXY WEB /static/style/style.min.css?v=807166c81ded9672f91872a576572dcd to http://jupyterhub:8080
jupyterhub | [I 2019-04-09 17:20:33.875 JupyterHub log:158] 302 GET /static/style/style.min.css?v=807166c81ded9672f91872a576572dcd -> /hub/static/style/style.min.css?v=807166c81ded9672f91872a576572dcd (@::ffff:73.70.187.70) 0.53ms
jupyterhub | 17:20:33.936 - debug: [ConfigProxy] PROXY WEB /custom/custom.css to http://jupyterhub:8080
jupyterhub | [I 2019-04-09 17:20:33.939 JupyterHub log:158] 302 GET /custom/custom.css -> /hub/custom/custom.css (@::ffff:73.70.187.70) 0.56ms
jupyterhub | 17:20:34.012 - debug: [ConfigProxy] PROXY WEB /static/components/es6-promise/promise.min.js?v=f004a16cb856e0ff11781d01ec5ca8fe to http://jupyterhub:8080
jupyterhub | 17:20:34.013 - debug: [ConfigProxy] PROXY WEB /hub/static/components/jquery-ui/themes/smoothness/jquery-ui.min.css?v=9b2c8d3489227115310662a343fce11c to http://jupyterhub:8080
jupyterhub | [I 2019-04-09 17:20:34.015 JupyterHub log:158] 302 GET /static/components/es6-promise/promise.min.js?v=f004a16cb856e0ff11781d01ec5ca8fe -> /hub/static/components/es6-promise/promise.min.js?v=f004a16cb856e0ff11781d01ec5ca8fe (@::ffff:73.70.187.70) 0.59ms
jupyterhub | [W 2019-04-09 17:20:34.016 JupyterHub log:158] 404 GET /hub/static/components/jquery-ui/themes/smoothness/jquery-ui.min.css?v=9b2c8d3489227115310662a343fce11c (@::ffff:73.70.187.70) 0.56ms
jupyterhub | 17:20:34.054 - debug: [ConfigProxy] PROXY WEB /hub/static/components/jquery-typeahead/dist/jquery.typeahead.min.css?v=7afb461de36accb1aa133a1710f5bc56 to http://jupyterhub:8080
jupyterhub | [W 2019-04-09 17:20:34.056 JupyterHub log:158] 404 GET /hub/static/components/jquery-typeahead/dist/jquery.typeahead.min.css?v=7afb461de36accb1aa133a1710f5bc56 (@::ffff:73.70.187.70) 0.59ms
jupyterhub | 17:20:34.174 - debug: [ConfigProxy] PROXY WEB /hub/static/style/style.min.css?v=807166c81ded9672f91872a576572dcd to http://jupyterhub:8080
jupyterhub | 17:20:34.175 - debug: [ConfigProxy] PROXY WEB /hub/custom/custom.css to http://jupyterhub:8080
jupyterhub | [W 2019-04-09 17:20:34.177 JupyterHub log:158] 404 GET /hub/static/style/style.min.css?v=807166c81ded9672f91872a576572dcd (@::ffff:73.70.187.70) 0.66ms
jupyterhub | [W 2019-04-09 17:20:34.211 JupyterHub log:158] 404 GET /hub/custom/custom.css (almore.cato@::ffff:73.70.187.70) 33.70ms
jupyterhub | 17:20:34.257 - debug: [ConfigProxy] PROXY WEB /static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce to http://jupyterhub:8080
jupyterhub | [I 2019-04-09 17:20:34.260 JupyterHub log:158] 302 GET /static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce -> /hub/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce (@::ffff:73.70.187.70) 0.57ms
jupyterhub | 17:20:34.263 - debug: [ConfigProxy] PROXY WEB /user/logo to http://jupyterhub:8080
jupyterhub | 17:20:34.264 - debug: [ConfigProxy] PROXY WEB /hub/static/components/es6-promise/promise.min.js?v=f004a16cb856e0ff11781d01ec5ca8fe to http://jupyterhub:8080
jupyterhub | [I 2019-04-09 17:20:34.265 JupyterHub log:158] 302 GET /user/logo -> /user/logo/ (@::ffff:73.70.187.70) 0.48ms
jupyterhub | [W 2019-04-09 17:20:34.266 JupyterHub log:158] 404 GET /hub/static/components/es6-promise/promise.min.js?v=f004a16cb856e0ff11781d01ec5ca8fe (@::ffff:73.70.187.70) 0.50ms
jupyterhub | 17:20:34.562 - debug: [ConfigProxy] PROXY WEB /user/logo/ to http://jupyterhub:8080
jupyterhub | [I 2019-04-09 17:20:34.564 JupyterHub log:158] 302 GET /user/logo/ -> /hub/user/logo/ (@::ffff:73.70.187.70) 0.57ms
jupyterhub | 17:20:34.974 - debug: [ConfigProxy] PROXY WEB /hub/user/logo/ to http://jupyterhub:8080
jupyterhub | [W 2019-04-09 17:20:34.984 JupyterHub web:1667] 404 GET /hub/user/logo/ (::ffff:73.70.187.70): No such user logo
jupyterhub | [W 2019-04-09 17:20:34.985 JupyterHub log:158] 404 GET /hub/user/logo/ (almore.cato@::ffff:73.70.187.70) 8.93ms
```

Docker Compose File
```
# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# JupyterHub docker-compose configuration file
version: "2"

services:
  hub:
    build:
      context: .
      dockerfile: Dockerfile.jupyterhub
      args:
        JUPYTERHUB_VERSION: ${JUPYTERHUB_VERSION}
    restart: always
    image: jupyterhub
    container_name: jupyterhub
    volumes:
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      - "data:${DATA_VOLUME_CONTAINER}"
    ports:
      - "8443:8443"
    #links:
      #- hub-db
    environment:
      # All containers will join this network
      DOCKER_NETWORK_NAME: ${DOCKER_NETWORK_NAME}
      # JupyterHub will spawn this Notebook image for users
      DOCKER_NOTEBOOK_IMAGE: ${LOCAL_NOTEBOOK_IMAGE}
      # Notebook directory inside user image
      DOCKER_NOTEBOOK_DIR: ${DOCKER_NOTEBOOK_DIR}
      # Using this run command (optional)
      DOCKER_SPAWN_CMD: ${DOCKER_SPAWN_CMD}
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py

volumes:
  data:
    external:
      name: ${DATA_VOLUME_HOST}

networks:
  default:
    external:
      name: ${DOCKER_NETWORK_NAME}

```

Docker.jupyterhub File
```
# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
ARG JUPYTERHUB_VERSION
FROM jupyterhub/jupyterhub-onbuild:$JUPYTERHUB_VERSION

# Install dockerspawner, oauth, postgres
RUN /opt/conda/bin/conda install -yq psycopg2=2.7 && \
    /opt/conda/bin/conda clean -tipsy && \
    /opt/conda/bin/pip install --no-cache-dir \
        oauthenticator==0.8.* \
        dockerspawner==0.10.*

# Copy TLS certificate and key
ENV SSL_CERT /srv/jupyterhub/secrets/jupyterhub.crt
ENV SSL_KEY /srv/jupyterhub/secrets/jupyterhub.key
COPY ./secrets/jupyterhub-crt.pem $SSL_CERT
COPY ./secrets/jupyterhub-key.pem $SSL_KEY
RUN chmod 700 /srv/jupyterhub/secrets && \
    chmod 600 /srv/jupyterhub/secrets/*

COPY ./userlist /srv/jupyterhub/userlist

RUN for name in almore.cato; do useradd -m -p $(openssl passwd -1 'testpassword') $name; done
```

Jupyter Config looks like this:

```
# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# Configuration file for JupyterHub
import os

c = get_config()

# We rely on environment variables to configure JupyterHub so that we
# avoid having to rebuild the JupyterHub container every time we change a
# configuration parameter.

# Spawn single-user servers as Docker containers
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
# Spawn containers from this image
c.DockerSpawner.container_image = os.environ['DOCKER_NOTEBOOK_IMAGE']

# JupyterHub requires a single-user instance of the Notebook server, so we
# default to using the `start-singleuser.sh` script included in the
# jupyter/docker-stacks *-notebook images as the Docker run command when
# spawning containers.  Optionally, you can override the Docker run command
# using the DOCKER_SPAWN_CMD environment variable.
spawn_cmd = os.environ.get('DOCKER_SPAWN_CMD', "start-singleuser.sh")
c.DockerSpawner.extra_create_kwargs.update({ 'command': spawn_cmd })

# Connect containers to this Docker network
network_name = os.environ['DOCKER_NETWORK_NAME']
c.DockerSpawner.use_internal_ip = True
c.DockerSpawner.network_name = network_name
# Pass the network name as argument to spawned containers
c.DockerSpawner.extra_host_config = { 'network_mode': network_name }
# Explicitly set notebook directory because we'll be mounting a host volume to
# it.  Most jupyter/docker-stacks *-notebook images run the Notebook server as
# user `jovyan`, and set the notebook directory to `/home/jovyan/work`.
# We follow the same convention.
notebook_dir = os.environ.get('DOCKER_NOTEBOOK_DIR') or '/home/jovyan/work'
c.DockerSpawner.notebook_dir = notebook_dir
# Mount the real user's Docker volume on the host to the notebook user's
# notebook directory in the container
c.DockerSpawner.volumes = { 'jupyterhub-user-{username}': notebook_dir }

# Remove containers once they are stopped
c.DockerSpawner.remove_containers = True
# For debugging arguments passed to spawned containers
c.DockerSpawner.debug = True

# User containers will access hub by container name on the Docker network
c.JupyterHub.hub_ip = 'jupyterhub'
c.JupyterHub.hub_port = 8080

# TLS config
c.JupyterHub.port = 8443
c.JupyterHub.ssl_key = os.environ['SSL_KEY']
c.JupyterHub.ssl_cert = os.environ['SSL_CERT']

# Persist hub data on volume mounted inside container
data_dir = os.environ.get('DATA_VOLUME_CONTAINER', '/data')

c.JupyterHub.cookie_secret_file = os.path.join(data_dir,
    'jupyterhub_cookie_secret')

c.PAMAuthenticator.open_sessions = False
c.JupyterHub.debug_proxy = True

# Whitlelist users and admins
c.Authenticator.whitelist = whitelist = set()
c.Authenticator.admin_users = admin = set()
c.JupyterHub.admin_access = True
pwd = os.path.dirname(__file__)
with open(os.path.join(pwd, 'userlist')) as f:
    for line in f:
        if not line:
            continue
        parts = line.split()
        # in case of newline at the end of userlist file
        if len(parts) >= 1:
            name = parts[0]
            whitelist.add(name)
            if len(parts) > 1 and parts[1] == 'admin':
                admin.add(name)
```

**Comment by playermanny2** [comment]
Updated to jupyterhub --pre 0.9.4 (same version as hub is using) on my custom image.

Now receiving error... any ideas?

```
fatal: destination path '/home/jovyan/work/notebook_count' already exists and is not an empty directory.                                                                     Traceback (most recent call last):                                                                                                                                             File "/opt/conda/bin/jupyterhub-singleuser", line 3, in                                                                                                                from jupyterhub.singleuser import main                                                                                                                                     File "/opt/conda/lib/python3.5/site-packages/jupyterhub/singleuser.py", line 13, in                                                                                    from tornado.httpclient import AsyncHTTPClient                                                                                                                             File "/opt/conda/lib/python3.5/site-packages/tornado/httpclient.py", line 46, in                                                                                       from tornado.concurrent import (                                                                                                                                           File "/opt/conda/lib/python3.5/site-packages/tornado/concurrent.py", line 34, in                                                                                       from tornado.log import app_log                                                                                                                                            File "/opt/conda/lib/python3.5/site-packages/tornado/log.py", line 34, in                                                                                              from tornado.escape import _unicode                                                                                                                                        File "/opt/conda/lib/python3.5/site-packages/tornado/escape.py", line 27, in                                                                                           from tornado.util import unicode_type                                                                                                                                      File "/opt/conda/lib/python3.5/site-packages/tornado/util.py", line 21, in                                                                                             from typing import (                                                                                                                                                     ImportError: cannot import name 'Type'
--



```

**Comment by playermanny2** [comment]
Fixed By:

1. using jupyterhub/jupyterhub as base jupyterhub image rather than jupyterhub/jupyterhub-onbuild
2. Reverted to jupyter/minimal-notebook
3. added lines ```notebook_image``` to build file to ensure that that the docker compose make would rebuild the minimal with jupyterhub installed

This ultimately seemed like an issue with jupyterhub on my docker spawned container images(as i was using a custom image) not matching with jupyterhub container. I would suggest starting from a minimal build jupyter image, then once working start building your custom image.

Carpe Diem
