### ISSUE TITLE
pull_image fails if docker regsitry not on port 443

### ISSUE THREAD

**Issue by timhughes** [jupyterhub/dockerspawner#313]
When using a registry that is not on port 443 the method `DockerSpawner.pull_image`  https://github.com/jupyterhub/dockerspawner/blob/522a63fcc5706e9fce5ff759b6cccb9ae1afe312/dockerspawner/dockerspawner.py#L900  naively splits on the first `:` to find the tag. 

This causes the following error

```
jupyterhub | [I 2019-06-10 14:42:27.021 JupyterHub log:174] 302 GET /hub/spawn/hughest -> /hub/spawn-pending/hughest (hughest@::ffff:192.168.250.1) 217.05ms
jupyterhub | ERROR:asyncio:Task exception was never retrieved
jupyterhub | future: <Task finished coro=<BaseHandler.spawn_single_user() done, defined at /usr/local/python/lib/python3.7/site-packages/jupyterhub/handlers/base.py:697> exception=APIError(HTTPError('400 Client Error: Bad Request for url: http+docker://localhost/v1.39/images/create?tag=8443%2Fhughest%2Fvagrant-puppet-docker-jupyterhub%2Fjupyterlab&fromImage=git.timhughes.org'))>
jupyterhub | Traceback (most recent call last):
jupyterhub |   File "/usr/local/python/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
jupyterhub |     response.raise_for_status()
jupyterhub |   File "/usr/local/python/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
jupyterhub |     raise HTTPError(http_error_msg, response=self)
jupyterhub | requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.39/images/create?tag=8443%2Fhughest%2Fvagrant-puppet-docker-jupyterhub%2Fjupyterlab&fromImage=git.timhughes.org
```

**Comment by timhughes** [comment]
Here is some pretty ugly code as a quick fix but there are probably more edge cases.


```python
tests = [
    ("jupyterlab", "jupyterlab|latest"),
    ("jupyterlab:testing", "jupyterlab|testing"),
    ("jupyterhub/jupyterlab", "jupyterhub/jupyterlab|latest"),
    ("jupyterhub/jupyterlab:testing", "jupyterhub/jupyterlab|testing"),
    ("git.yb.lmax:8443/hughest/vagrant-puppet-docker-jupyterhub/jupyterlab", "git.yb.lmax:8443/hughest/vagrant-puppet-docker-jupyterhub/jupyterlab|latest"),
    ("git.yb.lmax:8443/hughest/vagrant-puppet-docker-jupyterhub/jupyterlab:testing", "git.yb.lmax:8443/hughest/vagrant-puppet-docker-jupyterhub/jupyterlab|testing"),
]
```


```python
def pull_image(image):
    if ':' in image:
        repo, tag = image.split(':', 1)
    else:
        repo = image
        tag = 'latest'
        
    return("{repo}|{tag}".format(repo=repo, tag=tag))
```


```python
for test in tests:
    print("Testing: {}".format(test[0]))
    if pull_image(test[0]) != test[1]:
        print("   -> Error: {} != {}".format(test[0],test[1]))
```

    Testing: jupyterlab
    Testing: jupyterlab:testing
    Testing: jupyterhub/jupyterlab
    Testing: jupyterhub/jupyterlab:testing
    Testing: git.yb.lmax:8443/hughest/vagrant-puppet-docker-jupyterhub/jupyterlab
       -> Error: git.yb.lmax:8443/hughest/vagrant-puppet-docker-jupyterhub/jupyterlab != git.yb.lmax:8443/hughest/vagrant-puppet-docker-jupyterhub/jupyterlab|latest
    Testing: git.yb.lmax:8443/hughest/vagrant-puppet-docker-jupyterhub/jupyterlab:testing
       -> Error: git.yb.lmax:8443/hughest/vagrant-puppet-docker-jupyterhub/jupyterlab:testing != git.yb.lmax:8443/hughest/vagrant-puppet-docker-jupyterhub/jupyterlab|testing



```python
def pull_image2(image):
    
    if ':' in image:
        if '/' in image: 
            trailer = image.rsplit('/', 1)[1]
            if ':' in trailer:
                repo, tag = image.rsplit(':', 1)
            else:
                repo = image
                tag = 'latest'
        else:
            repo, tag = image.rsplit(':', 1)
    else:
        repo = image
        tag = 'latest'
        
    return("{repo}|{tag}".format(repo=repo, tag=tag))

```


```python
for test in tests:
    print("Testing: {}".format(test[0]))
    if pull_image2(test[0]) != test[1]:
        print("   -> Error: {} != {}".format(test[0],test[1]))
```

    Testing: jupyterlab
    Testing: jupyterlab:testing
    Testing: jupyterhub/jupyterlab
    Testing: jupyterhub/jupyterlab:testing
    Testing: git.yb.lmax:8443/hughest/vagrant-puppet-docker-jupyterhub/jupyterlab
    Testing: git.yb.lmax:8443/hughest/vagrant-puppet-docker-jupyterhub/jupyterlab:testing

**Comment by timhughes** [comment]
Thanks
