### ISSUE TITLE
RuntimeError: Service jupyter-jovyan not found

### ISSUE THREAD

**Issue by shizidushu** [jupyterhub/dockerspawner#362]
I had issue #263, I tried to subclass `SwarmSpawner` to solve it. Then this new error appears.
Here is some line of jupyterhub_config.py
```
notebook_dir = os.environ.get('DOCKER_NOTEBOOK_DIR') or '/home/jovyan/work'
c.SwarmSpawner2.notebook_dir = notebook_dir
c.SwarmSpawner2.volumes = { '/home/bi/simon/jupyterhub-docker/jupyterhub_data/notebook/{username}': notebook_dir }
c.SwarmSpawner2.debug = True
```
The docker-compose.yml
```yml
version: '3'

services:
  jupyterhub:
    image: shizidushu/jupyterhub
    # This is necessary to prevent the singleton hub from using its service number as its hostname
    hostname: jupyterhub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jupyterhub_data:/srv/jupyterhub
      - /home/bi/simon/jupyterhub-docker/jupyterhub_data/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - /home/bi/simon/jupyterhub-docker/jupyterhub_data/cull_idle_servers.py:/srv/jupyterhub/cull_idle_servers.py
    environment:
      - DOCKER_JUPYTER_CONTAINER=shizidushu/jupyterlab:1.0
      - DOCKER_NETWORK_NAME=jupyterhub_network
      - DOCKER_NOTEBOOK_DIR=/home/jovyan
      - HUB_IP=jupyterhub
      - HUB_CONNECT_IP=jupyterhub
    ports:
      - "8000:8000"
      - "8080:8080"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - jupyterhub_network

  jupyterlab:
    image: shizidushu/jupyterlab:1.0
    command: echo
    networks:
      - jupyterhub_network


networks:
  jupyterhub_network:
    driver: overlay
    external: true

volumes:
  jupyterhub_data:
```

The log:
```pytz
[I 2020-03-26 14:38:48.245 JupyterHub app:2291] Running JupyterHub version 1.2.0dev
[I 2020-03-26 14:38:48.246 JupyterHub app:2322] Using Authenticator: nativeauthenticator.nativeauthenticator.NativeAuthenticator
[I 2020-03-26 14:38:48.246 JupyterHub app:2322] Using Spawner: builtins.SwarmSpawner2
[I 2020-03-26 14:38:48.246 JupyterHub app:2322] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.2.0dev
[I 2020-03-26 14:38:48.253 JupyterHub app:1384] Loading cookie_secret from /srv/jupyterhub/jupyterhub_cookie_secret
[I 2020-03-26 14:38:48.268 JupyterHub proxy:461] Generating new CONFIGPROXY_AUTH_TOKEN
[I 2020-03-26 14:38:48.289 JupyterHub app:1690] Not using whitelist. Any authenticated user will be allowed.
[I 2020-03-26 14:38:48.376 JupyterHub app:2362] Initialized 0 spawners in 0.002 seconds
[W 2020-03-26 14:38:48.380 JupyterHub proxy:643] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2020-03-26 14:38:48.381 JupyterHub proxy:646] Starting proxy @ http://:8000
14:38:48.851 [ConfigProxy] info: Proxying http://*:8000 to (no default)
14:38:48.854 [ConfigProxy] info: Proxy API at http://127.0.0.1:8001/api/routes
14:38:48.909 [ConfigProxy] info: 200 GET /api/routes 
[I 2020-03-26 14:38:48.910 JupyterHub app:2607] Hub API listening on http://0.0.0.0:8080/hub/
[I 2020-03-26 14:38:48.910 JupyterHub app:2622] Starting managed service cull_idle
[I 2020-03-26 14:38:48.910 JupyterHub service:335] Starting service 'cull_idle': ['python3', '/srv/jupyterhub/cull_idle_servers.py', '--timeout=36000']
[I 2020-03-26 14:38:48.914 JupyterHub service:121] Spawning python3 /srv/jupyterhub/cull_idle_servers.py --timeout=36000
14:38:48.919 [ConfigProxy] info: 200 GET /api/routes 
[I 2020-03-26 14:38:48.919 JupyterHub proxy:320] Checking routes
[I 2020-03-26 14:38:48.920 JupyterHub proxy:400] Adding default route for Hub: / => http://0.0.0.0:8080
14:38:48.922 [ConfigProxy] info: Adding route / -> http://0.0.0.0:8080
14:38:48.922 [ConfigProxy] info: Route added / -> http://0.0.0.0:8080
14:38:48.923 [ConfigProxy] info: 201 POST /api/routes/ 
[I 2020-03-26 14:38:48.923 JupyterHub app:2682] JupyterHub is now running at http://:8000
[I 2020-03-26 14:38:49.126 JupyterHub log:178] 200 GET /hub/api/users (cull_idle@127.0.0.1) 71.89ms
[I 2020-03-26 14:39:01.742 JupyterHub dockerspawner:784] Service 'jupyter-jovyan' is gone
[I 2020-03-26 14:39:02.496 JupyterHub log:178] 302 GET /hub/spawn/jovyan -> /hub/spawn-pending/jovyan (jovyan@::ffff:10.255.0.3) 1078.16ms
[I 2020-03-26 14:39:02.524 JupyterHub pages:347] jovyan is pending spawn
[I 2020-03-26 14:39:02.571 JupyterHub log:178] 200 GET /hub/spawn-pending/jovyan (jovyan@::ffff:10.255.0.3) 51.38ms
[W 2020-03-26 14:39:11.495 JupyterHub base:950] User jovyan is slow to start (timeout=10)
[I 2020-03-26 14:39:30.814 JupyterHub dockerspawner:990] Created service jupyter-jovyan (id: s8p32ui) from image shizidushu/jupyterlab:1.0
[I 2020-03-26 14:39:30.814 JupyterHub dockerspawner:1013] Starting service jupyter-jovyan (id: s8p32ui)
[E 2020-03-26 14:39:30.824 JupyterHub user:640] Unhandled error starting jovyan's server: Service jupyter-jovyan not found
[E 2020-03-26 14:39:31.005 JupyterHub gen:599] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py:845> exception=RuntimeError('Service jupyter-jovyan not found',)> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 593, in error_callback
        future.result()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 852, in finish_user_spawn
        await spawn_future
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 656, in spawn
        raise e
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 560, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.6/dist-packages/dockerspawner/dockerspawner.py", line 1017, in start
        yield self.start_object()
      File "/usr/local/lib/python3.6/dist-packages/dockerspawner/swarmspawner.py", line 252, in start_object
        raise RuntimeError("Service %s not found" % self.service_name)
    RuntimeError: Service jupyter-jovyan not found
    
[I 2020-03-26 14:39:31.009 JupyterHub log:178] 200 GET /hub/api/users/jovyan/server/progress (jovyan@::ffff:10.255.0.3) 28324.95ms
```

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

I’m especially closing old “how to” or debugging questions to keep the Issues list to bug reports and feature requests. These can be directed to [the Jupyter forum](http://discourse.jupyter.org) if still relevant.

I think it's useful to check [docker events](https://docs.docker.com/engine/reference/commandline/events/) to see what's going on.
