### ISSUE TITLE
cull_idle_servers 400s with an already-removed container

### ISSUE THREAD

**Issue by anderoonies** [jupyterhub/dockerspawner#424]
### Bug description

With `auto_remove` in host configuration, the `cull_idle_servers` service will occasionally 400 when attempting to cull users and oauth for containers that have been removed.

Excerpt of logs (jupyter-<> is user naming scheme):
```
[I 2021-04-12 16:33:51.339 JupyterHub dockerspawner:452] Container 'jupyter-6366' is gone
[I 2021-04-12 16:33:51.342 JupyterHub dockerspawner:452] Container 'jupyter-3233' is gone
[I 2021-04-12 16:33:51.342 JupyterHub dockerspawner:452] Container 'jupyter-3915' is gone
[I 2021-04-12 16:33:51.344 JupyterHub dockerspawner:452] Container 'jupyter-5976' is gone
[I 2021-04-12 16:33:51.344 JupyterHub dockerspawner:452] Container 'jupyter-1208' is gone
[I 2021-04-12 16:33:51.344 JupyterHub dockerspawner:452] Container 'jupyter-9911' is gone
[I 2021-04-12 16:33:51.345 JupyterHub dockerspawner:452] Container 'jupyter-74' is gone
[I 2021-04-12 16:33:51.345 JupyterHub dockerspawner:452] Container 'jupyter-1104' is gone
[I 2021-04-12 16:33:51.345 JupyterHub dockerspawner:452] Container 'jupyter-170' is gone
[W 2021-04-12 16:33:51.346 JupyterHub dockerspawner:423] container not found
[W 2021-04-12 16:33:51.346 JupyterHub dockerspawner:423] container not found
[W 2021-04-12 16:33:51.346 JupyterHub dockerspawner:423] container not found
[W 2021-04-12 16:33:51.379 JupyterHub dockerspawner:423] container not found
[W 2021-04-12 16:33:51.382 JupyterHub dockerspawner:423] container not found
[W 2021-04-12 16:33:51.382 JupyterHub dockerspawner:423] container not found
[W 2021-04-12 16:33:51.382 JupyterHub dockerspawner:423] container not found
[W 2021-04-12 16:33:51.383 JupyterHub dockerspawner:423] container not found
[W 2021-04-12 16:33:51.383 JupyterHub dockerspawner:423] container not found
[W 2021-04-12 16:33:51.383 JupyterHub web:1786] 400 DELETE /hub/api/users/6366/server (10.1.56.120): 6366 is not running
[W 2021-04-12 16:33:51.387 JupyterHub log:158] 400 DELETE /hub/api/users/6366/server (cull-idle@10.1.56.120) 375.96ms
[W 2021-04-12 16:33:51.388 JupyterHub web:1786] 400 DELETE /hub/api/users/3233/server (10.1.56.120): 3233 is not running
[W 2021-04-12 16:33:51.391 JupyterHub log:158] 400 DELETE /hub/api/users/3233/server (cull-idle@10.1.56.120) 378.22ms
[W 2021-04-12 16:33:51.391 JupyterHub web:1786] 400 DELETE /hub/api/users/3915/server (10.1.56.120): 3915 is not running
[E 210412 16:33:51 cull_idle_servers:300] Error processing 3915
    Traceback (most recent call last):
      File "cull_idle_servers.py", line 298, in cull_idle
        result = yield f
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "cull_idle_servers.py", line 234, in handle_user
        results = yield multi(server_futures)
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 501, in callback
        result_list.append(f.result())
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "cull_idle_servers.py", line 194, in handle_server
        resp = yield fetch(req)
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 748, in run
        yielded = self.gen.send(value)
      File "cull_idle_servers.py", line 110, in fetch
        return (yield client.fetch(req))
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
    tornado.httpclient.HTTPClientError: HTTP 400: Bad Request
[E 210412 16:33:51 cull_idle_servers:300] Error processing 3233
    Traceback (most recent call last):
      File "cull_idle_servers.py", line 298, in cull_idle
        result = yield f
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "cull_idle_servers.py", line 234, in handle_user
        results = yield multi(server_futures)
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 501, in callback
        result_list.append(f.result())
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "cull_idle_servers.py", line 194, in handle_server
        resp = yield fetch(req)
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 748, in run
        yielded = self.gen.send(value)
      File "cull_idle_servers.py", line 110, in fetch
        return (yield client.fetch(req))
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
    tornado.httpclient.HTTPClientError: HTTP 400: Bad Request
```

### Your personal set up

 - OS:
ubuntu 18.04
 - Version(s):
dockerspawner==0.9.1
jupyterhub==0.9.1

- <details><summary>Configuration</summary>

```python
# jupyterhub_config.py
c.JupyterHub.authenticator_class = 'tmpauthenticator.TmpAuthenticator'
# ...
# culling
c.JupyterHub.last_activity_interval = 120
c.JupyterHub.services = [
    {
        'name': 'cull-idle',
        'admin': True,
	    'command': 'python3 cull_idle_servers.py --timeout=160 --cull_users=true'.split(),
    }
]
```
</details>

**Comment by minrk** [comment]
> Version(s):
dockerspawner==0.9.1
jupyterhub==0.9.1

After running some tests, I noticed these are both pretty far out-of-date. I *believe* this is fixed already (specifically by [this change](https://github.com/jupyterhub/jupyterhub/pull/2154/files#diff-f734cfb896739ad90c75be9f70c244ac66b9133acf57f9f0b419c265aeb647c0L399-R426), if you can update to more recent versions of both packages.

Current are:

- dockerspawner 12.0 (big changes in container/volume naming, so careful there)
- jupyterhub 1.3

**Comment by anderoonies** [comment]
Good to know, I’ll test with up-to-date versions today.

**Comment by anderoonies** [comment]
still testing this but it appears to have been fixed, thanks!
