### ISSUE TITLE
CI: test (3.8, internal-ssl) is unreliable

### ISSUE THREAD

**Issue by manics** [jupyterhub/dockerspawner#445]
### Bug description
The `test (3.8, internal-ssl)` gitHub workflow is unreliable, it fails intermittently. Rerunning the workflow usually results in it passing.

#### Expected behaviour
Test should reliably pass

#### Actual behaviour
Test intermittently fails. Example:
```
2021-11-25T11:58:54.0047351Z ==================================== ERRORS ====================================
2021-11-25T11:58:54.0048084Z _____________________ ERROR at setup of test_internal_ssl ______________________
2021-11-25T11:58:54.0048702Z 
2021-11-25T11:58:54.0049301Z volumes_and_networks = None, compose_build = None
2021-11-25T11:58:54.0049712Z 
2021-11-25T11:58:54.0050474Z     @pytest.fixture(scope='session')
2021-11-25T11:58:54.0051215Z     def compose_up(volumes_and_networks, compose_build):
2021-11-25T11:58:54.0052169Z         p = Popen(['docker-compose', 'up'], cwd=here)
2021-11-25T11:58:54.0052747Z         for i in range(60):
2021-11-25T11:58:54.0053176Z             try:
2021-11-25T11:58:54.0053902Z                 r = requests.get(hub_url + '/hub/')
2021-11-25T11:58:54.0054512Z >               r.raise_for_status()
2021-11-25T11:58:54.0054835Z 
2021-11-25T11:58:54.0055281Z test_internal_ssl.py:57: 
2021-11-25T11:58:54.0055899Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2021-11-25T11:58:54.0057669Z 
2021-11-25T11:58:54.0058155Z self = <Response [404]>
2021-11-25T11:58:54.0058464Z 
2021-11-25T11:58:54.0058914Z     def raise_for_status(self):
2021-11-25T11:58:54.0059579Z         """Raises :class:`HTTPError`, if one occurred."""
2021-11-25T11:58:54.0060088Z     
2021-11-25T11:58:54.0060799Z         http_error_msg = ''
2021-11-25T11:58:54.0061391Z         if isinstance(self.reason, bytes):
2021-11-25T11:58:54.0062368Z             # We attempt to decode utf-8 first because some servers
2021-11-25T11:58:54.0063189Z             # choose to localize their reason strings. If the string
2021-11-25T11:58:54.0064151Z             # isn't utf-8, we fall back to iso-8859-1 for all other
2021-11-25T11:58:54.0064791Z             # encodings. (See PR #3538)
2021-11-25T11:58:54.0065267Z             try:
2021-11-25T11:58:54.0066038Z                 reason = self.reason.decode('utf-8')
2021-11-25T11:58:54.0066779Z             except UnicodeDecodeError:
2021-11-25T11:58:54.0067746Z                 reason = self.reason.decode('iso-8859-1')
2021-11-25T11:58:54.0068321Z         else:
2021-11-25T11:58:54.0068798Z             reason = self.reason
2021-11-25T11:58:54.0069275Z     
2021-11-25T11:58:54.0069759Z         if 400 <= self.status_code < 500:
2021-11-25T11:58:54.0070818Z             http_error_msg = u'%s Client Error: %s for url: %s' % (self.status_code, reason, self.url)
2021-11-25T11:58:54.0071456Z     
2021-11-25T11:58:54.0071942Z         elif 500 <= self.status_code < 600:
2021-11-25T11:58:54.0073041Z             http_error_msg = u'%s Server Error: %s for url: %s' % (self.status_code, reason, self.url)
2021-11-25T11:58:54.0073666Z     
2021-11-25T11:58:54.0074089Z         if http_error_msg:
2021-11-25T11:58:54.0074788Z >           raise HTTPError(http_error_msg, response=self)
2021-11-25T11:58:54.0076007Z E           requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:8000/hub/
2021-11-25T11:58:54.0076744Z 
2021-11-25T11:58:54.0077919Z /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/requests/models.py:953: HTTPError
2021-11-25T11:58:54.0078573Z 
2021-11-25T11:58:54.0079650Z During handling of the above exception, another exception occurred:
2021-11-25T11:58:54.0080202Z 
2021-11-25T11:58:54.0080791Z volumes_and_networks = None, compose_build = None
2021-11-25T11:58:54.0081198Z 
2021-11-25T11:58:54.0081934Z     @pytest.fixture(scope='session')
2021-11-25T11:58:54.0082673Z     def compose_up(volumes_and_networks, compose_build):
2021-11-25T11:58:54.0083618Z         p = Popen(['docker-compose', 'up'], cwd=here)
2021-11-25T11:58:54.0084210Z         for i in range(60):
2021-11-25T11:58:54.0084620Z             try:
2021-11-25T11:58:54.0085339Z                 r = requests.get(hub_url + '/hub/')
2021-11-25T11:58:54.0085914Z                 r.raise_for_status()
2021-11-25T11:58:54.0086432Z             except Exception:
2021-11-25T11:58:54.0086957Z                 time.sleep(1)
2021-11-25T11:58:54.0087489Z                 if p.poll() is not None:
2021-11-25T11:58:54.0088468Z >                   raise RuntimeError("`docker-compose up` failed")
2021-11-25T11:58:54.0089541Z E                   RuntimeError: `docker-compose up` failed
2021-11-25T11:58:54.0090167Z 
2021-11-25T11:58:54.0090712Z test_internal_ssl.py:61: RuntimeError
2021-11-25T11:58:54.0091456Z =========================== short test summary info ============================
2021-11-25T11:58:54.0093163Z ERROR test_internal_ssl.py::test_internal_ssl - RuntimeError: `docker-compose...
2021-11-25T11:58:54.0094118Z !!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
2021-11-25T11:58:54.0094817Z ============================== 1 error in 39.44s ===============================
```

### How to reproduce
Run the GitHub CI tests in the `main` branch
https://github.com/jupyterhub/dockerspawner/blob/a4625a1d34c15e18abb766db1becf89f80eece13/.github/workflows/test.yml#L98-L102

**Comment by minrk** [comment]
Probably a timeout or race in starting things up. Should at least capture docker-compose output when it fails so we can debug.

**Comment by minrk** [comment]
Ah, we do capture the output, and it is a race / circular dependency where the hub needs the proxy and the proxy needs the hub - they'll eventually figure it out, but it might give up before they resolve. I'll see if I can figure out how to make it more consistent in the docker-compose setup.

<details>

```
Pulling proxy (jupyterhub/configurable-http-proxy:4.3.1)...
194
4.3.1: Pulling from jupyterhub/configurable-http-proxy
195
Digest: sha256:4c2c995879c398d2bb663604f27f6c033f3aad94cdc2fa92ec7e6c5b09cff8f9
196
Status: Downloaded newer image for jupyterhub/configurable-http-proxy:4.3.1
197
Creating proxy ... 
198
Creating proxy ... done
199
Creating jupyterhub ... 
200
Creating jupyterhub ... done
201
Attaching to proxy, jupyterhub
202
proxy    | internal/fs/utils.js:307
203
proxy    |     throw err;
204
proxy    |     ^
205
proxy    | 
206
proxy    | Error: ENOENT: no such file or directory, open '/jupyterhub-ssl/certs/proxy-api/proxy-api.key'
207
proxy    |     at Object.openSync (fs.js:476:3)
208
proxy    |     at Object.readFileSync (fs.js:377:35)
209
proxy    |     at Object.<anonymous> (/srv/configurable-http-proxy/bin/configurable-http-proxy:211:29)
210
proxy    |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
211
proxy    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
212
proxy    |     at Module.load (internal/modules/cjs/loader.js:928:32)
213
proxy    |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
214
proxy    |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
215
proxy    |     at internal/main/run_main_module.js:17:47 {
216
proxy    |   errno: -2,
217
proxy    |   syscall: 'open',
218
proxy    |   code: 'ENOENT',
219
proxy    |   path: '/jupyterhub-ssl/certs/proxy-api/proxy-api.key'
220
proxy    | }
221
proxy exited with code 1
222
jupyterhub | Waiting for proxy: [Errno -2] Name or service not known
223
proxy    | internal/fs/utils.js:307
224
proxy    |     throw err;
225
proxy    |     ^
226
proxy    | 
227
proxy    | Error: ENOENT: no such file or directory, open '/jupyterhub-ssl/certs/proxy-api/proxy-api.key'
228
proxy    |     at Object.openSync (fs.js:476:3)
229
proxy    |     at Object.readFileSync (fs.js:377:35)
230
proxy    |     at Object.<anonymous> (/srv/configurable-http-proxy/bin/configurable-http-proxy:211:29)
231
proxy    |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
232
proxy    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
233
proxy    |     at Module.load (internal/modules/cjs/loader.js:928:32)
234
proxy    |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
235
proxy    |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
236
proxy    |     at internal/main/run_main_module.js:17:47 {
237
proxy    |   errno: -2,
238
proxy    |   syscall: 'open',
239
proxy    |   code: 'ENOENT',
240
proxy    |   path: '/jupyterhub-ssl/certs/proxy-api/proxy-api.key'
241
proxy    | }
242
jupyterhub | [I 2021-11-26 12:58:29.764 JupyterHub app:2349] Running JupyterHub version 1.3.0
243
jupyterhub | [I 2021-11-26 12:58:29.765 JupyterHub app:2379] Using Authenticator: jupyterhub.auth.DummyAuthenticator-1.3.0
244
jupyterhub | [I 2021-11-26 12:58:29.765 JupyterHub app:2379] Using Spawner: dockerspawner.dockerspawner.DockerSpawner-12.2.0dev
245
jupyterhub | [I 2021-11-26 12:58:29.765 JupyterHub app:2379] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.3.0
246
jupyterhub | [D 2021-11-26 12:58:29.782 JupyterHub app:1460] Generating new cookie_secret
247
jupyterhub | [I 2021-11-26 12:58:29.786 JupyterHub app:1465] Writing cookie_secret to /data/jupyterhub_cookie_secret
248
jupyterhub | [I 2021-11-26 12:58:30.210 JupyterHub app:1525] Adding CA for hub-internal: IP:127.0.0.1;DNS:localhost;DNS:6cf9c5205e38;DNS:jupyterhub;DNS:proxy
249
proxy    | internal/fs/utils.js:307
250
proxy    |     throw err;
301
jupyterhub |       File "/usr/local/lib/python3.8/dist-packages/jupyterhub/proxy.py", line 808, in _wait_for_api_request
302
jupyterhub |         return await client.fetch(req)
303
jupyterhub |       File "/usr/local/lib/python3.8/dist-packages/tornado/simple_httpclient.py", line 338, in run
304
jupyterhub |         stream = await self.tcp_client.connect(
305
jupyterhub |       File "/usr/local/lib/python3.8/dist-packages/tornado/tcpclient.py", line 265, in connect
306
jupyterhub |         addrinfo = await self.resolver.resolve(host, port, af)
307
jupyterhub |       File "/usr/local/lib/python3.8/dist-packages/tornado/netutil.py", line 398, in resolve
308
jupyterhub |         result = await IOLoop.current().run_in_executor(
309
jupyterhub |       File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
310
jupyterhub |         result = self.fn(*self.args, **self.kwargs)
311
jupyterhub |       File "/usr/local/lib/python3.8/dist-packages/tornado/netutil.py", line 382, in _resolve_addr
312
jupyterhub |         addrinfo = socket.getaddrinfo(host, port, family, socket.SOCK_STREAM)
313
jupyterhub |       File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
314
jupyterhub |         for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
315
jupyterhub |     socket.gaierror: [Errno -3] Temporary failure in name resolution
316
jupyterhub |     
317
jupyterhub | [D 2021-11-26 12:58:30.768 JupyterHub application:834] Exiting application: jupyterhub
318
```
</details>
