### ISSUE TITLE
Example's in this Repo don't work...

### ISSUE THREAD

**Issue by cablesky** [jupyterhub/dockerspawner#452]
I'm having big trouble running the examples in this repo (dockerspawner/examples).
I tested the "Swarm" example (https://github.com/jupyterhub/dockerspawner/tree/main/examples/swarm)

I just added the following line to the "jupyterhub_config.py" file:

> c.SwarmSpawner.image = 'jupyter/base-notebook'

(otherwise nothing would have worked)

The following log files were output:

**Notebook-Log:**

> Patching auth into jupyter_server.base.handlers.JupyterHandler(jupyter_server.base.handlers.AuthenticatedHandler) -> JupyterHandler(jupyterhub.singleuser.mixins.HubAuthenticatedHandler, jupyter_server.base.handlers.AuthenticatedHandler),
Patching auth into notebook.base.handlers.IPythonHandler(notebook.base.handlers.AuthenticatedHandler) -> IPythonHandler(jupyterhub.singleuser.mixins.HubAuthenticatedHandler, notebook.base.handlers.AuthenticatedHandler),
[I 2022-04-04 07:12:08.058 SingleUserLabApp mixins:614] Starting jupyterhub single-user server version 2.2.2,
[I 2022-04-04 07:12:08.058 SingleUserLabApp mixins:628] Extending jupyterlab.labhubapp.SingleUserLabApp from jupyterlab 3.3.2,
[I 2022-04-04 07:12:08.058 SingleUserLabApp mixins:628] Extending jupyter_server.serverapp.ServerApp from jupyter_server 1.16.0,
[W 2022-04-04 07:12:08.070 SingleUserLabApp configurable:193] Config option `open_browser` not recognized by `SingleUserLabApp`.  Did you mean `browser`?,
[W 2022-04-04 07:12:08.083 SingleUserLabApp configurable:193] Config option `open_browser` not recognized by `SingleUserLabApp`.  Did you mean `browser`?,
[I 2022-04-04 07:12:08.084 SingleUserLabApp manager:340] jupyterlab | extension was successfully linked.,
[W 2022-04-04 07:12:08.086 NotebookApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.,
[W 2022-04-04 07:12:08.086 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.,
[W 2022-04-04 07:12:08.086 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.,
[W 2022-04-04 07:12:08.092 SingleUserLabApp configurable:193] Config option `open_browser` not recognized by `SingleUserLabApp`.  Did you mean `browser`?,
[I 2022-04-04 07:12:08.092 SingleUserLabApp manager:340] nbclassic | extension was successfully linked.,
[I 2022-04-04 07:12:08.220 SingleUserLabApp manager:340] notebook_shim | extension was successfully linked.,
[I 2022-04-04 07:12:08.238 SingleUserLabApp manager:362] notebook_shim | extension was successfully loaded.,
[I 2022-04-04 07:12:08.240 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.9/site-packages/jupyterlab,
[I 2022-04-04 07:12:08.240 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab,
[I 2022-04-04 07:12:08.243 SingleUserLabApp manager:362] jupyterlab | extension was successfully loaded.,
[I 2022-04-04 07:12:08.246 SingleUserLabApp manager:362] nbclassic | extension was successfully loaded.,
[I 2022-04-04 07:12:08.247 SingleUserLabApp mixins:640] Starting jupyterhub-singleuser server version 2.2.2,
[W 2022-04-04 07:12:08.252 SingleUserLabApp _version:68] jupyterhub version 1.3.0 != jupyterhub-singleuser version 2.2.2. This could cause failure to authenticate and result in redirect loops!,
[I 2022-04-04 07:12:08.253 SingleUserLabApp serverapp:2670] Serving notebooks from local directory: /home/jovyan,
[I 2022-04-04 07:12:08.253 SingleUserLabApp serverapp:2670] Jupyter Server 1.16.0 is running at:,
[I 2022-04-04 07:12:08.253 SingleUserLabApp serverapp:2670] http://346cec9303f9:8888/user/test/lab,
[I 2022-04-04 07:12:08.253 SingleUserLabApp serverapp:2670]  or http://127.0.0.1:8888/user/test/lab,
[I 2022-04-04 07:12:08.253 SingleUserLabApp serverapp:2671] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).,
[I 2022-04-04 07:12:08.256 SingleUserLabApp mixins:596] Updating Hub with activity every 300 seconds,
[W 2022-04-04 07:12:22.243 SingleUserLabApp log:189] 404 GET /api (@127.0.0.1) 14.74ms,
[W 2022-04-04 07:12:37.329 SingleUserLabApp log:189] 404 GET /api (@127.0.0.1) 0.79ms,
[W 2022-04-04 07:12:52.420 SingleUserLabApp log:189] 404 GET /api (@127.0.0.1) 0.74ms,
[C 2022-04-04 07:12:54.766 SingleUserLabApp serverapp:2120] received signal 15, stopping,
[I 2022-04-04 07:12:54.767 SingleUserLabApp serverapp:2459] Shutting down 3 extensions,
[I 2022-04-04 07:12:54.768 SingleUserLabApp serverapp:2433] Shutting down 0 kernels,
[I 2022-04-04 07:12:54.768 SingleUserLabApp serverapp:2450] Shutting down 0 terminals

**Jupyter-Hub-Log:**

> ons   
[D 2022-04-04 07:11:50.202 JupyterHub log:181] 200 GET /hub/static/js/home.js?v=20220404070853 (@::ffff:10.0.2.2) 2.65ms
[D 2022-04-04 07:11:50.445 JupyterHub log:181] 200 GET /hub/static/components/moment/moment.js?v=20220404070853 (@::ffff:10.0.2.2) 11.61ms
[D 2022-04-04 07:11:50.558 JupyterHub log:181] 200 GET /hub/static/js/jhapi.js?v=20220404070853 (@::ffff:10.0.2.2) 6.81ms
[D 2022-04-04 07:11:50.595 JupyterHub log:181] 200 GET /hub/static/js/utils.js?v=20220404070853 (@::ffff:10.0.2.2) 1.06ms
[D 2022-04-04 07:11:51.541 JupyterHub pages:217] Triggering spawn with default options for test
[D 2022-04-04 07:11:51.542 JupyterHub base:875] Initiating spawn for test
[D 2022-04-04 07:11:51.542 JupyterHub base:879] 0/100 concurrent spawns
[D 2022-04-04 07:11:51.543 JupyterHub base:884] 0 active servers
[D 2022-04-04 07:11:51.571 JupyterHub user:602] Calling Spawner.start for test
[D 2022-04-04 07:11:51.573 JupyterHub dockerspawner:1200] Skipping pull of jupyter/base-notebook
[D 2022-04-04 07:11:51.575 JupyterHub dockerspawner:992] Getting service 'jupyter-test'
[I 2022-04-04 07:11:51.579 JupyterHub dockerspawner:998] Service 'jupyter-test' is gone
[I 2022-04-04 07:11:51.587 JupyterHub dockerspawner:1282] Created service jupyter-test (id: 4bq7w8p) from image jupyter/base-notebook
[I 2022-04-04 07:11:51.588 JupyterHub dockerspawner:1306] Starting service jupyter-test (id: 4bq7w8p)
[D 2022-04-04 07:11:51.589 JupyterHub swarmspawner:155] Getting task of service 'jupyter-test'
[D 2022-04-04 07:11:51.590 JupyterHub dockerspawner:992] Getting service 'jupyter-test'
[D 2022-04-04 07:11:51.594 JupyterHub swarmspawner:280] Service 4bq7w8p state: pending
[I 2022-04-04 07:11:52.545 JupyterHub log:181] 302 GET /hub/spawn/test -> /hub/spawn-pending/test (test@::ffff:10.0.2.2) 1008.46ms
[I 2022-04-04 07:11:52.552 JupyterHub pages:402] test is pending spawn
[D 2022-04-04 07:11:52.554 JupyterHub log:181] 304 GET /hub/spawn-pending/test (test@::ffff:10.0.2.2) 4.94ms
[D 2022-04-04 07:11:52.596 JupyterHub swarmspawner:155] Getting task of service 'jupyter-test'
[D 2022-04-04 07:11:52.598 JupyterHub dockerspawner:992] Getting service 'jupyter-test'
[D 2022-04-04 07:11:52.604 JupyterHub swarmspawner:280] Service 4bq7w8p state: preparing
[D 2022-04-04 07:11:54.108 JupyterHub swarmspawner:155] Getting task of service 'jupyter-test'
[D 2022-04-04 07:11:54.110 JupyterHub dockerspawner:992] Getting service 'jupyter-test'
[D 2022-04-04 07:11:54.128 JupyterHub swarmspawner:280] Service 4bq7w8p state: preparing
[D 2022-04-04 07:11:56.381 JupyterHub swarmspawner:155] Getting task of service 'jupyter-test'
[D 2022-04-04 07:11:56.381 JupyterHub dockerspawner:992] Getting service 'jupyter-test'
[D 2022-04-04 07:11:56.402 JupyterHub swarmspawner:280] Service 4bq7w8p state: preparing
[D 2022-04-04 07:11:59.780 JupyterHub swarmspawner:155] Getting task of service 'jupyter-test'
[D 2022-04-04 07:11:59.780 JupyterHub dockerspawner:992] Getting service 'jupyter-test'
[D 2022-04-04 07:11:59.787 JupyterHub swarmspawner:280] Service 4bq7w8p state: preparing
[W 2022-04-04 07:12:01.545 JupyterHub base:1003] User test is slow to start (timeout=10)
[D 2022-04-04 07:12:04.852 JupyterHub swarmspawner:155] Getting task of service 'jupyter-test'
[D 2022-04-04 07:12:04.852 JupyterHub dockerspawner:992] Getting service 'jupyter-test'
[D 2022-04-04 07:12:04.857 JupyterHub swarmspawner:280] Service 4bq7w8p state: preparing
[I 2022-04-04 07:12:08.251 JupyterHub log:181] 200 GET /hub/api (@10.0.4.35) 0.41ms
[D 2022-04-04 07:12:08.259 JupyterHub base:283] Recording first activity for <APIToken('3e9e...', user='test')>
[D 2022-04-04 07:12:08.273 JupyterHub users:765] Activity for user test: 2022-04-04T07:12:08.228314Z
[D 2022-04-04 07:12:08.274 JupyterHub users:783] Activity on server test/: 2022-04-04T07:12:08.228314Z
[I 2022-04-04 07:12:08.278 JupyterHub log:181] 200 POST /hub/api/users/test/activity (test@10.0.4.35) 20.41ms
[D 2022-04-04 07:12:12.452 JupyterHub swarmspawner:155] Getting task of service 'jupyter-test'
[D 2022-04-04 07:12:12.452 JupyterHub dockerspawner:992] Getting service 'jupyter-test'
[D 2022-04-04 07:12:12.472 JupyterHub swarmspawner:280] Service 4bq7w8p state: starting
[D 2022-04-04 07:12:23.474 JupyterHub swarmspawner:155] Getting task of service 'jupyter-test'
[D 2022-04-04 07:12:23.475 JupyterHub dockerspawner:992] Getting service 'jupyter-test'
[D 2022-04-04 07:12:23.488 JupyterHub swarmspawner:280] Service 4bq7w8p state: starting
[D 2022-04-04 07:12:34.491 JupyterHub swarmspawner:155] Getting task of service 'jupyter-test'
[D 2022-04-04 07:12:34.491 JupyterHub dockerspawner:992] Getting service 'jupyter-test'
[D 2022-04-04 07:12:34.511 JupyterHub swarmspawner:280] Service 4bq7w8p state: starting
[D 2022-04-04 07:12:45.514 JupyterHub swarmspawner:155] Getting task of service 'jupyter-test'
[D 2022-04-04 07:12:45.514 JupyterHub dockerspawner:992] Getting service 'jupyter-test'
[D 2022-04-04 07:12:45.531 JupyterHub swarmspawner:280] Service 4bq7w8p state: starting
[W 2022-04-04 07:12:51.575 JupyterHub user:681] test's server failed to start in 60 seconds, giving up
[D 2022-04-04 07:12:51.576 JupyterHub user:790] Stopping test
[D 2022-04-04 07:12:51.576 JupyterHub swarmspawner:155] Getting task of service 'jupyter-test'
[D 2022-04-04 07:12:51.576 JupyterHub dockerspawner:992] Getting service 'jupyter-test'
[D 2022-04-04 07:12:51.594 JupyterHub swarmspawner:144] Service 4bq7w8p status: {'ContainerStatus': {'ContainerID': '346cec9303f9390adef22d86f88a3380ec182ae1ce22c02c256ae9df81768517',
                         'ExitCode': 0,
                         'PID': 0},
     'Message': 'starting',
     'PortStatus': {},
     'State': 'starting',
     'Timestamp': '2022-04-04T07:12:06.809782407Z'}
[I 2022-04-04 07:12:51.596 JupyterHub dockerspawner:1400] Stopping service jupyter-test (id: 4bq7w8p)
[I 2022-04-04 07:12:51.597 JupyterHub swarmspawner:257] Removing service 4bq7w8pcq0794tdjot286hulo
[D 2022-04-04 07:12:51.619 JupyterHub user:816] Deleting oauth client jupyterhub-user-test
[D 2022-04-04 07:12:51.624 JupyterHub user:819] Finished stopping test
[E 2022-04-04 07:12:51.630 JupyterHub gen:623] Exception in Future <Task finished name='Task-63' coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py:895> exception=TimeoutError('Timeout')> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 618, in error_callback
        future.result()
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 902, in finish_user_spawn
        await spawn_future
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/user.py", line 707, in spawn
        raise e
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/user.py", line 606, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
    tornado.util.TimeoutError: Timeout
[I 2022-04-04 07:12:51.633 JupyterHub log:181] 200 GET /hub/api/users/test/server/progress (test@::ffff:10.0.2.2) 57820.25ms
[D 2022-04-04 07:12:56.533 JupyterHub swarmspawner:155] Getting task of service 'jupyter-test'
[D 2022-04-04 07:12:56.533 JupyterHub dockerspawner:992] Getting service 'jupyter-test'
[I 2022-04-04 07:12:56.545 JupyterHub dockerspawner:998] Service 'jupyter-test' is gone
[E 2022-04-04 07:12:56.545 JupyterHub gen:623] Exception in Future <Task finished name='Task-64' coro=<DockerSpawner.start() done, defined at /usr/local/lib/python3.8/dist-packages/dockerspawner/dockerspawner.py:1231> exception=RuntimeError('Service jupyter-test not found')> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 618, in error_callback
        future.result()
      File "/usr/local/lib/python3.8/dist-packages/dockerspawner/dockerspawner.py", line 1314, in start
        await self.start_object()
      File "/usr/local/lib/python3.8/dist-packages/dockerspawner/swarmspawner.py", line 276, in start_object
        raise RuntimeError("Service %s not found" % self.service_name)

Can someone tell me what is the problem here?
I think the API access doesn't work. (because of "404 GET /api (@127.0.0.1)".
Thank you in advance!

**Comment by minrk** [comment]
I believe this is the key log:

> [I 2022-04-04 07:12:08.247 SingleUserLabApp mixins:640] Starting jupyterhub-singleuser server version 2.2.2,
[W 2022-04-04 07:12:08.252 SingleUserLabApp _version:68] jupyterhub version 1.3.0 != jupyterhub-singleuser version 2.2.2. This could cause failure to authenticate and result in redirect loops!,

The default version in the example is 1.3, while the version of jupyterhub in your chosen image is 2.2.2. This can cause incompatibility. The versions are updated in #454 and the example works again.

**Comment by cablesky** [comment]
Thank you. JupyterHub an Notebook must be the same Version! This was the problem!
