### ISSUE TITLE
Not able to log to jupyterhub notebook as admin 

### ISSUE THREAD

**Issue by Sireeshabotta** [jupyterhub/dockerspawner#491]
My jupyterhub instance is running in a docker container. not able to login to the jupyterhub as admin. i created a user 
adduser <username>  and provided the privileges to the user. but when i signed in to the jupytehub notebook the admin block is not available.

i even tired this, docker exec -it jupyterhub bash and then passwd root to set the password of root.
After that, i tried to login with  the username "root" and password. However, root admin always returned "Spawn failed" error.
Only normal user which is created in docker container can get spawn successfully.

Did anyone know the solution?

<img width="1503" alt="Screenshot 2023-07-06 at 14 56 15" src="https://github.com/jupyterhub/dockerspawner/assets/52789113/b2d4ac10-b710-4d49-926d-7a824caf9780">

<img width="1509" alt="Screenshot 2023-07-06 at 15 02 16" src="https://github.com/jupyterhub/dockerspawner/assets/52789113/0c07efa2-5438-4ddb-b01e-3011e92bf8e0">

**Comment by christina-seegers** [comment]
I found myself in a similar situation although I did not try with a root user. The singleserver does not start for some users. All those users are part of the same Group.  I created that goup to give access a service but that prevents the singleservers to be created. The panel for administration can be accessed in my case so it is somewhat different. 

Just in case this might help someone, this is part of the logfile that I get:
...
jupyterhub                          | [D 2023-09-05 12:57:46.267 JupyterHub dockerspawner:982] Getting container 'jupyter-instructor2'
jupyterhub                          | [I 2023-09-05 12:57:46.269 JupyterHub dockerspawner:988] Container 'jupyter-instructor2' is gone
jupyterhub                          | [W 2023-09-05 12:54:43.374 JupyterHub dockerspawner:963] Container not found: jupyter-instructor2
jupyterhub                          | Task exception was never retrieved
jupyterhub                          | future: <Task finished name='Task-115662' coro=<BaseHandler.spawn_single_user() done, defined at /usr/local/lib/python3.10/dist-packages/jupyterhub/handlers/base.py:869> exception=HTTPError()>
jupyterhub                          | Traceback (most recent call last):
jupyterhub                          |   File "/usr/local/lib/python3.10/dist-packages/jupyterhub/handlers/base.py", line 1076, in spawn_single_user
jupyterhub                          |     await gen.with_timeout(
jupyterhub                          | asyncio.exceptions.TimeoutError: Timeout
jupyterhub                          |
jupyterhub                          |
jupyterhub                          | During handling of the above exception, another exception occurred:
jupyterhub                          |
jupyterhub                          |
jupyterhub                          | Traceback (most recent call last):
jupyterhub                          |   File "/usr/local/lib/python3.10/dist-packages/jupyterhub/handlers/base.py", line 1110, in spawn_single_user
jupyterhub                          |     raise web.HTTPError(
jupyterhub                          | tornado.web.HTTPError: HTTP 500: Internal Server Error (Spawner failed to start [status=0]. The logs for instructor2 may contain details.)
jupyterhub                          | [D 2023-09-05 12:58:06.508 JupyterHub dockerspawner:982] Getting container 'jupyter-instructor2'
jupyterhub                          | [I 2023-09-05 12:58:06.510 JupyterHub dockerspawner:988] Container 'jupyter-instructor2' is gone
jupyterhub                          | [W 2023-09-05 12:58:06.510 JupyterHub dockerspawner:963] Container not found: jupyter-instructor2
jupyterhub                          | [W 2023-09-05 12:58:10.803 JupyterHub user:933] instructor2's server never showed up at http://172.24.0.3:8888/user/instructor2/ after 30 seconds. Giving up.
jupyterhub                          |
jupyterhub                          |     Common causes of this timeout, and debugging tips:
jupyterhub                          |
jupyterhub                          |     1. The server didn't finish starting,
jupyterhub                          |        or it crashed due to a configuration issue.
jupyterhub                          |        Check the single-user server's logs for hints at what needs fixing.
jupyterhub                          |     2. The server started, but is not accessible at the specified URL.
jupyterhub                          |        This may be a configuration issue specific to your chosen Spawner.
jupyterhub                          |        Check the single-user server logs and resource to make sure the URL
jupyterhub                          |        is correct and accessible from the Hub.
jupyterhub                          |     3. (unlikely) Everything is working, but the server took too long to respond.
jupyterhub                          |        To fix: increase `Spawner.http_timeout` configuration
jupyterhub                          |        to a number of seconds that is enough for servers to become responsive.
jupyterhub                          |
jupyterhub                          | [D 2023-09-05 12:58:10.803 JupyterHub user:982] Stopping instructor2
jupyterhub                          | [D 2023-09-05 12:58:10.803 JupyterHub dockerspawner:982] Getting container 'jupyter-instructor2'
jupyterhub                          | [I 2023-09-05 12:58:10.805 JupyterHub dockerspawner:988] Container 'jupyter-instructor2' is gone
jupyterhub                          | [W 2023-09-05 12:58:10.805 JupyterHub dockerspawner:963] Container not found: jupyter-instructor2
jupyterhub                          | [D 2023-09-05 12:58:10.812 JupyterHub user:1002] Deleting oauth client jupyterhub-user-instructor2
jupyterhub                          | [D 2023-09-05 12:58:10.817 JupyterHub user:1005] Finished stopping instructor2
...

**Comment by GorML** [comment]
> I found myself in a similar situation although I did not try with a root user. The singleserver does not start for some users. All those users are part of the same Group. I created that goup to give access a service but that prevents the singleservers to be created. The panel for administration can be accessed in my case so it is somewhat different.
> 
> Just in case this might help someone, this is part of the logfile that I get: ... jupyterhub | [D 2023-09-05 12:57:46.267 JupyterHub dockerspawner:982] Getting container 'jupyter-instructor2' jupyterhub | [I 2023-09-05 12:57:46.269 JupyterHub dockerspawner:988] Container 'jupyter-instructor2' is gone jupyterhub | [W 2023-09-05 12:54:43.374 JupyterHub dockerspawner:963] Container not found: jupyter-instructor2 jupyterhub | Task exception was never retrieved jupyterhub | future: <Task finished name='Task-115662' coro=<BaseHandler.spawn_single_user() done, defined at /usr/local/lib/python3.10/dist-packages/jupyterhub/handlers/base.py:869> exception=HTTPError()> jupyterhub | Traceback (most recent call last): jupyterhub | File "/usr/local/lib/python3.10/dist-packages/jupyterhub/handlers/base.py", line 1076, in spawn_single_user jupyterhub | await gen.with_timeout( jupyterhub | asyncio.exceptions.TimeoutError: Timeout jupyterhub | jupyterhub | jupyterhub | During handling of the above exception, another exception occurred: jupyterhub | jupyterhub | jupyterhub | Traceback (most recent call last): jupyterhub | File "/usr/local/lib/python3.10/dist-packages/jupyterhub/handlers/base.py", line 1110, in spawn_single_user jupyterhub | raise web.HTTPError( jupyterhub | tornado.web.HTTPError: HTTP 500: Internal Server Error (Spawner failed to start [status=0]. The logs for instructor2 may contain details.) jupyterhub | [D 2023-09-05 12:58:06.508 JupyterHub dockerspawner:982] Getting container 'jupyter-instructor2' jupyterhub | [I 2023-09-05 12:58:06.510 JupyterHub dockerspawner:988] Container 'jupyter-instructor2' is gone jupyterhub | [W 2023-09-05 12:58:06.510 JupyterHub dockerspawner:963] Container not found: jupyter-instructor2 jupyterhub | [W 2023-09-05 12:58:10.803 JupyterHub user:933] instructor2's server never showed up at http://172.24.0.3:8888/user/instructor2/ after 30 seconds. Giving up. jupyterhub | jupyterhub | Common causes of this timeout, and debugging tips: jupyterhub | jupyterhub | 1. The server didn't finish starting, jupyterhub | or it crashed due to a configuration issue. jupyterhub | Check the single-user server's logs for hints at what needs fixing. jupyterhub | 2. The server started, but is not accessible at the specified URL. jupyterhub | This may be a configuration issue specific to your chosen Spawner. jupyterhub | Check the single-user server logs and resource to make sure the URL jupyterhub | is correct and accessible from the Hub. jupyterhub | 3. (unlikely) Everything is working, but the server took too long to respond. jupyterhub | To fix: increase `Spawner.http_timeout` configuration jupyterhub | to a number of seconds that is enough for servers to become responsive. jupyterhub | jupyterhub | [D 2023-09-05 12:58:10.803 JupyterHub user:982] Stopping instructor2 jupyterhub | [D 2023-09-05 12:58:10.803 JupyterHub dockerspawner:982] Getting container 'jupyter-instructor2' jupyterhub | [I 2023-09-05 12:58:10.805 JupyterHub dockerspawner:988] Container 'jupyter-instructor2' is gone jupyterhub | [W 2023-09-05 12:58:10.805 JupyterHub dockerspawner:963] Container not found: jupyter-instructor2 jupyterhub | [D 2023-09-05 12:58:10.812 JupyterHub user:1002] Deleting oauth client jupyterhub-user-instructor2 jupyterhub | [D 2023-09-05 12:58:10.817 JupyterHub user:1005] Finished stopping instructor2 ...

Did you solve the problem?
